/* GENERATED by scripts/build-content.mjs from content/ — do not edit.
   Edit content/projects/*.md and run `node scripts/build-content.mjs`.
   Case study content — condensed from the full Notion case studies. */
window.CASE_STUDIES = {
  "portfolio-system": {
    index: "01 / This site",
    title: "Portfolio as a Product",
    subtitle:
      "Every claim on this page is inspectable in the same public repository that renders it. If the system were not real, this page could not exist in the shape it does.",
    meta: ["Designer & Builder", "Design system", "AI-first", "Storybook", "Figma push", "Open source"],
    accentMeta: ["Open source"],
    content: `
      <h3>The idea</h3>
      <p>A designer's portfolio usually <strong>describes</strong> process. This one <strong>demonstrates</strong> it: every button, chip, and square on this page comes from a design system that lives in the same public repository, documents itself for AI agents, and ships automatically. If I claim to build AI-ready systems, the claim should be inspectable.</p>

      <h3>The system</h3>
      <ul>
        <li><strong>Repo-first tokens.</strong> One JSON file is the only place a colour is born. A zero-dependency script generates the CSS variables this very page loads, plus a machine-readable flat file for AI agents and the Figma push.</li>
        <li><strong>Every component is three things.</strong> A CSS block, an AI spec (canonical HTML pattern + do/don't rules), and a Storybook story. The build fails if any of the three is missing — governance as a 90-line script, not a platform.</li>
        <li><strong>The skeleton is the concept.</strong> A 24-square sheet whose rails are real square divs sized by the layout's own fr-tracks — and Conway's Game of Life lives on them. Click a square: the life you seed is born blueprint-blue and its lineage fades to stone.</li>
      </ul>

      <h3>The pipeline</h3>
      <figure style="border: 1px solid var(--chrome-border-strong); background: var(--surface-raised); padding: 1.25rem; margin: 1.5rem 0; color: var(--content-primary); max-width: none;">
        <svg viewBox="0 0 800 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Pipeline: tokens.json builds to dist, consumed by the site, Storybook, Figma and AI agents; GitHub auto-deploys both apps to Vercel" style="width:100%;height:auto;display:block;font-family:ui-monospace,monospace">
          <g fill="none" stroke="currentColor" stroke-width="1.5">
            <rect x="20"  y="30" width="150" height="44"/>
            <rect x="240" y="30" width="150" height="44"/>
            <rect x="460" y="30" width="150" height="44"/>
            <path d="M170 52h62m0 0-8-5m8 5-8 5"/>
            <path d="M390 52h62m0 0-8-5m8 5-8 5"/>
            <path d="M535 74v28"/>
            <path d="M60 130h680" stroke-dasharray="4 4" stroke-width="1"/>
            <path d="M110 130v34m0 0-5-8m5 8 5-8"/>
            <path d="M310 130v34m0 0-5-8m5 8 5-8"/>
            <path d="M510 130v34m0 0-5-8m5 8 5-8"/>
            <path d="M690 130v34m0 0-5-8m5 8 5-8"/>
            <rect x="35"  y="164" width="150" height="44"/>
            <rect x="235" y="164" width="150" height="44"/>
            <rect x="435" y="164" width="150" height="44"/>
            <rect x="635" y="164" width="130" height="44"/>
            <rect x="20"  y="262" width="200" height="44"/>
            <path d="M220 284h96m0 0-8-5m8 5-8 5"/>
            <rect x="316" y="262" width="200" height="44"/>
            <path d="M110 208v54"/>
            <path d="M310 208v54"/>
          </g>
          <g fill="currentColor" font-size="13" text-anchor="middle">
            <text x="95"  y="56">tokens.json</text>
            <text x="315" y="56">build.mjs</text>
            <text x="535" y="56">dist/</text>
            <text x="110" y="190">THE SITE</text>
            <text x="310" y="190">STORYBOOK</text>
            <text x="510" y="190">FIGMA VARS</text>
            <text x="700" y="190">AI AGENTS</text>
            <text x="120" y="288">GITHUB (main)</text>
            <text x="416" y="288">VERCEL ×2</text>
          </g>
          <g fill="currentColor" font-size="10" opacity="0.65" text-anchor="middle">
            <text x="95"  y="90">source of truth</text>
            <text x="315" y="90">zero deps</text>
            <text x="535" y="90">css + flat.json</text>
            <text x="510" y="222">one-way, via MCP</text>
            <text x="700" y="222">spec.md files</text>
            <text x="268" y="254">auto-deploy on push</text>
          </g>
        </svg>
        <figcaption class="mono" style="font-size:.68rem;letter-spacing:.08em;text-transform:uppercase;color:var(--chrome-label);margin-top:.75rem">One source of truth, four consumers, no manual steps between commit and production.</figcaption>
      </figure>
      <ul>
        <li><strong>GitHub → Vercel.</strong> Two deployments from one public repo: this site (pure static, no build) and the Storybook, rebuilt on every push to main.</li>
        <li><strong>Repo → Figma.</strong> Tokens flow one way — an AI agent pushes them as Figma Variables following a written, idempotent procedure. Figma is an output, never a source.</li>
        <li><strong>Repo → AI.</strong> CLAUDE.md routes any agent to the system's README and per-component specs; an agent can assemble correct UI from the canonical patterns without seeing the site first.</li>
      </ul>

      <h3>Receipts</h3>
      <p><span class="stat">0</span></p>
      <ul>
        <li><strong>0 accessibility violations</strong> across the component library — axe-audited per story, WCAG 2.1 AA contrast decisions documented inside the tokens themselves, and verified in <em>both</em> themes.</li>
        <li><strong>83 tokens, 147 values, 21 components</strong> — one token carries its light, dark and print values together; each component is enforced as CSS + AI spec + story by the build.</li>
        <li><strong>Dark mode is 23 tokens and zero component rules.</strong> A themed colour carries its dark value beside its light one; the build emits the media query and the pinned-theme override. There is no <code>prefers-color-scheme</code> anywhere in the component CSS — the sharpest test a semantic token layer can be put to.</li>
        <li><strong>No build step in the site.</strong> Two link tags consume the system; view-source shows everything.</li>
      </ul>

      <div class="ph-grid">
        <figure class="ph"><span class="ph__label">Storybook — component library live</span></figure>
        <figure class="ph"><span class="ph__label">Figma — variables after the first push</span></figure>
      </div>

      <h3>See for yourself</h3>
      <p>
        <a class="btn btn--solid" href="https://github.com/yordanhristovUX/yordan-portfolio" target="_blank" rel="noopener" style="margin-right:.6rem">GitHub repo ↗</a>
        <a class="btn" href="https://yordan-design-system.vercel.app" target="_blank" rel="noopener" style="margin-right:.6rem">Storybook ↗</a>
        <a class="btn" href="evals.html" style="margin-right:.6rem">Retrieval evaluation →</a>
        <a class="btn" href="mcp.html">MCP server →</a>
      </p>
    `,
  },

  "greenstreet-ds": {
    index: "02 / Green Street",
    title: "AI-ready design systems and Agentic workflows",
    subtitle:
      "Infrastructure that lets AI generate production-faithful UI: 1:1 Figma-to-code parity, custom Claude skills, and a prototype pipeline for the whole TPM team.",
    meta: ["Senior Product Designer", "Design Systems", "AI Workflows", "Figma-to-code", "WCAG", "Production code"],
    accentMeta: ["Production code"],
    content: `
      <figure class="ph"><span class="ph__label">Cover — design system overview, 1600×900</span></figure>

      <h3>The problem</h3>
      <p>Green Street is a leading commercial real estate data and analytics company. I was brought in to redesign the AI Assistant module, and found that PM wireframes, design files, and coded components lived in separate worlds — a component could look one way in Figma and behave completely differently in production.</p>
      <ul>
        <li><strong>Fragmented handoff.</strong> No enforced relationship between mockups, design, and code.</li>
        <li><strong>AI couldn't read the system.</strong> Every AI-generated UI drifted from the actual components.</li>
        <li><strong>No prototype pipeline.</strong> TPMs pulled design resources into every minor exploration.</li>
      </ul>

      <h3>The approach</h3>
      <p><strong>Audit and architecture.</strong> A full audit of the component landscape — duplication, inconsistency, missing states, accessibility failures — then a token-first architecture with semantic naming. Every component exposes its full range of states, so AI and developers never need to guess.</p>
      <p><strong>1:1 Figma-to-code parity.</strong> A Figma library of <strong>~35 components and growing</strong>, each mapping exactly to a coded component: same name, same props, same variants. I drove the alignment with engineering — attending standups and reviewing implementations to catch drift early.</p>
      <p><strong>Tokens in the frontend, not just the design file.</strong> I implemented the tokens directly in the frontend component library, replacing every hardcoded value for <strong>100% token coverage across the module</strong>. A design system that only exists in Figma is a picture of a design system.</p>
      <p><strong>A living style guide.</strong> Every token and every component, rendered from the real implementation — used for visual regression testing and for design-to-code comparison, so drift is something you can see rather than something you discover in review.</p>
      <p><strong>Custom Claude skills.</strong> A persistent knowledge layer that teaches Claude to read the token structure, assemble the correct native components, respect spacing and hierarchy, and generate prototypes faithful to the real system. No drift. No invented components.</p>
      <p><strong>TPM prototype pipeline.</strong> A PM describes a screen; the pipeline assembles a working interactive prototype from real system components. The feedback loop between product thinking and validated interaction went from days to minutes.</p>

      <h3>Shipping production code</h3>
      <p>I authored the complete responsive navigation component for the Green Street Analytics platform — built with Claude Code guided by the custom skills, reviewed and approved by the engineering team, and live in production. Not a prototype: production frontend code serving real users.</p>

      <div class="ph-grid">
        <figure class="ph"><span class="ph__label">Figma library — components &amp; tokens</span></figure>
        <figure class="ph"><span class="ph__label">Shipped navigation, live in production</span></figure>
      </div>

      <h3>Outcomes</h3>
      <ul>
        <li>TPMs generate accurate prototypes without design involvement in every cycle.</li>
        <li>A single source of truth between Figma and code — translation ambiguity eliminated.</li>
        <li>Every new component added becomes immediately AI-accessible.</li>
        <li>A design-to-code pipeline in progress: from Figma screen to reviewed frontend implementation.</li>
      </ul>
      <p>This work sits at the intersection of deep Figma craft, frontend architecture, and applied AI expertise — not using off-the-shelf tools, but building the tools themselves.</p>
    `,
  },

  "greenstreet-audit": {
    index: "03 / Green Street",
    title: "UX & Accessibility Audits",
    subtitle:
      "End-to-end WCAG 2.1 AA audits of two distinct product surfaces — an editorial platform and a data-dense analytics platform — with severity-rated, annotated remediation roadmaps.",
    meta: ["Senior Product Designer", "Accessibility", "UX Audit", "WCAG 2.1 AA", "Two products"],
    accentMeta: ["WCAG 2.1 AA"],
    content: `
      <figure class="ph"><span class="ph__label">Cover — annotated audit findings, 1600×900</span></figure>

      <h3>Why it matters here</h3>
      <p>Green Street's users are professional analysts, investors, and brokers making high-stakes financial decisions — many across multiple screens for hours, some with assistive technologies. For a data company, an unlabelled filter or a contrast failure isn't just an accessibility issue. It's a credibility gap.</p>

      <h3>Green Street News — editorial</h3>
      <ul>
        <li><strong>Colour contrast</strong> — systematic review against WCAG 2.1 AA thresholds across article bodies, bylines, timestamps, and navigation.</li>
        <li><strong>Semantic structure</strong> — heading hierarchy that means something to a screen reader, not just visually.</li>
        <li><strong>Keyboard navigation</strong> — focus traps, missing indicators, mouse-only elements.</li>
        <li><strong>Labelling</strong> — icon-only buttons, ambiguous "read more" links, unlabelled form controls.</li>
      </ul>

      <h3>Analytics &amp; Research Platform — data-dense</h3>
      <ul>
        <li><strong>Data tables</strong> — header scope, captions, sortable column accessibility, nested headers.</li>
        <li><strong>Charts</strong> — text alternatives, colour-only encoding, keyboard-accessible data views.</li>
        <li><strong>Filters &amp; faceted search</strong> — keyboard operability, focus management, live region announcements.</li>
        <li><strong>Dynamic content</strong> — explicit focus management for async loading, panels, and modals.</li>
        <li><strong>Full AA sweep</strong> — criterion-by-criterion review of all 50 AA success criteria.</li>
      </ul>

      <h3>Deliverables</h3>
      <p><span class="stat">200+</span></p>
      <p>Issue instances catalogued across the two surfaces. Every finding documented with a severity rating (Critical / Major / Minor), WCAG criterion reference, annotated screenshot, recommended fix, and estimated engineering effort — plus a mapping to the platform workflow it affects, so engineering unblocks the most-used analytical paths first. The output is a prioritised remediation roadmap, not a list of complaints.</p>

      <div class="ph-grid">
        <figure class="ph"><span class="ph__label">Findings report — severity ratings</span></figure>
        <figure class="ph"><span class="ph__label">Annotated Figma documentation</span></figure>
      </div>

      <h3>Outcomes</h3>
      <ul>
        <li>Both products now have a clear, actionable roadmap to WCAG 2.1 AA compliance.</li>
        <li>Cross-product observations shaped component prioritisation in the AI-ready design system — the most inconsistent patterns became the first to be standardised.</li>
        <li>A repeatable audit methodology for every new product surface as the platform grows.</li>
      </ul>
    `,
  },

  domestina: {
    index: "04 / Domestina.bg",
    title: "Cleaning Service Marketplace",
    subtitle:
      "A research-led, multi-year UX engagement on Bulgaria's leading cleaning services marketplace — every design change grounded in evidence, not assumption.",
    meta: ["UX Researcher & Designer", "UX Research", "Data-driven", "Marketplace", "Multi-year"],
    accentMeta: ["Data-driven"],
    content: `
      <figure class="ph"><span class="ph__label">Cover — front page redesign, 1600×900</span></figure>

      <h3>The brief</h3>
      <p>Three user types, three definitions of success: <strong>clients</strong> booking a service and deciding who to trust, <strong>service providers</strong> competing on reputation, and <strong>housemaids</strong> needing a low-friction onboarding path. The challenge: serve all three without making any of them feel second-class.</p>

      <h3>Research</h3>
      <p>Competitor analysis showed Domestina had no direct comprehensive competitor in the Bulgarian market — it had to define its own UX standards. Personas built from interviews, support tickets, Google Analytics, and Hotjar surfaced the critical insight: <strong>clients were anxious about inviting a stranger into their home.</strong> Trust signals weren't nice-to-haves — they were the primary conversion driver.</p>

      <h3>What I changed</h3>
      <ul>
        <li><strong>Front page redesign</strong> — restructured around the primary client action, trust signals moved above the fold, provider recruitment split into its own entry point.</li>
        <li><strong>Domestina Club</strong> — loyalty mechanics designed into existing flows without adding friction to conversion.</li>
        <li><strong>Provider workshops</strong> — made performance feedback clear and actionable, improving the whole provider pool.</li>
        <li><strong>Housemaid registration</strong> — progressive disclosure with named stages and visible momentum.</li>
      </ul>

      <div class="ph-grid">
        <figure class="ph"><span class="ph__label">Before — original front page</span></figure>
        <figure class="ph"><span class="ph__label">After — trust-first hierarchy</span></figure>
      </div>

      <h3>Measured outcomes</h3>
      <p><span class="stat">−40%</span></p>
      <ul>
        <li><strong>40% reduction in front page bounce rate</strong> — from a focused hierarchy redesign, not a full rebuild.</li>
        <li>Marked increase in completed housemaid registrations.</li>
        <li>Improved retention following the Domestina Club launch.</li>
        <li>Stronger provider performance after workshop-driven design changes.</li>
      </ul>
      <p>Not a single project — a continuous improvement methodology applied to a live, growing marketplace over multiple years.</p>
    `,
  },

  "malko-tarnovo": {
    index: "05 / Municipality of Malko Tarnovo",
    title: "Municipal Mobile App",
    subtitle:
      "End-to-end design of a cross-platform civic app serving two opposing audiences — tourists and older residents — live on the App Store and Google Play.",
    meta: ["Product Designer", "Shipped", "Design System", "iOS & Android", "White-label", "Accessibility"],
    accentMeta: ["Shipped"],
    content: `
      <figure class="ph"><span class="ph__label">Cover — app screens on device, 1600×900</span></figure>

      <h3>The challenge</h3>
      <p>Two audiences with almost opposing needs. <strong>Tourists</strong> are explorers — visual richness, maps, discovery flows. <strong>Local residents</strong>, many of them older, need municipal services: waste schedules, announcements, contacts — with large touch targets, minimal cognitive load, and zero ambiguity.</p>

      <h3>The dual colour logic</h3>
      <p><strong>Green</strong> encodes everything tourism — nature reserves, trails, gastronomy — connecting to the Strandzha region's identity. <strong>Blue</strong> encodes everything administrative, carrying the institutional calm of government services.</p>
      <p>This is not decoration; it's a wayfinding system. A user glancing at a card knows instantly whether it's a tourist recommendation or a municipal service — before reading a word. For older users, colour becomes a cognitive shortcut.</p>

      <h3>White-label design system</h3>
      <ul>
        <li><strong>Semantic colour tokens</strong> — swap the green/blue for any municipality's brand and it cascades through the entire system.</li>
        <li><strong>Spacing and rounding tokens</strong> — no arbitrary values anywhere in the library.</li>
        <li><strong>Typography system</strong> — Comfortaa, tokenised scale, friendly yet official.</li>
        <li><strong>Icon system</strong> — municipal logo redesigned on a 64×80 grid, coherent from app icon to in-app header.</li>
      </ul>

      <h3>Accessibility by default</h3>
      <ul>
        <li>Touch targets exceeding WCAG's 44×44px minimum throughout.</li>
        <li>WCAG 2.1 AA contrast across both colour contexts.</li>
        <li>Hierarchy through size, weight, and spacing — never colour alone.</li>
        <li>Progressive disclosure for dense municipal content.</li>
      </ul>

      <div class="ph-grid">
        <figure class="ph"><span class="ph__label">Tourism flow — green context</span></figure>
        <figure class="ph"><span class="ph__label">Municipal services — blue context</span></figure>
      </div>

      <h3>Outcomes</h3>
      <p>Launched on iOS and Android, publicly available on both stores. The white-label system is a reusable product — any Bulgarian municipality can deploy it with brand-token changes alone. The dual colour logic became a reference model for designing civic services for mixed-age audiences.</p>
      <a class="btn btn--solid" href="https://apps.apple.com/bg/app/malko-tarnovo-municipality/id6742865585" target="_blank" rel="noopener">View on the App Store ↗</a>
    `,
  },
};
