#!/usr/bin/env node
/* ============================================================
   Design system build — zero dependencies.

   tokens/tokens.json  →  dist/tokens.css       (:root custom properties,
                                                 consumed by the site + Storybook)
                       →  dist/tokens.flat.json (dotted keys with resolved
                                                 values, consumed by AI agents
                                                 and the Figma push procedure)
                       →  ../content/system.generated.json
                                                 (the system's own statistics,
                                                 consumed by scripts/build-content.mjs
                                                 so the prose that advertises them
                                                 has exactly one source)

   `node scripts/build.mjs`          build tokens + system stats
   `node scripts/build.mjs --check`  build + verify every component has
                                     spec.md and a story (coverage gate), and
                                     that the generated prose still quotes the
                                     current numbers (counts gate)

   Run order for the repo as a whole: this script first (it emits the stats),
   then `node scripts/build-content.mjs` from the repo root (it consumes them).
   ============================================================ */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const tokens = JSON.parse(readFileSync(join(root, "tokens", "tokens.json"), "utf8"));

/* ---------- normalize: every entry -> { value, dark?, print?, description? } ---------- */
const categories = [];
for (const [cat, entries] of Object.entries(tokens)) {
  if (cat.startsWith("$")) continue;
  const doc = entries.$doc ?? "";
  const vars = [];
  for (const [name, raw] of Object.entries(entries)) {
    if (name.startsWith("$")) continue;
    const { value, dark, print, description } =
      typeof raw === "string"
        ? { value: raw, dark: undefined, print: undefined, description: undefined }
        : raw;
    vars.push({ name, value, dark, print, description });
  }
  categories.push({ cat, doc, vars });
}

/* ---------- dist/tokens.css ----------
   Three blocks. :root carries the light theme and every theme-independent
   token. The dark overrides are emitted twice from the same source: once
   behind the OS preference (skipped when the visitor has pinned light) and
   once behind an explicit data-theme, so the control can override the OS in
   either direction. Anything without a `dark` value simply cascades. */
const pick = (key) =>
  categories.flatMap(({ cat, vars }) =>
    vars.filter((v) => v[key] !== undefined).map((v) => ({ ...v, cat }))
  );
const darkVars = pick("dark");
const printVars = pick("print");

let css = `/* GENERATED by scripts/build.mjs from tokens/tokens.json — do not edit.
   Edit tokens/tokens.json and run \`npm run build\`. */\n:root {\n`;
for (const { doc, vars } of categories) {
  if (doc) css += `\n  /* --- ${doc} --- */\n`;
  for (const v of vars) {
    css += `  --${v.name}: ${v.value};${v.description ? ` /* ${v.description} */` : ""}\n`;
  }
}
css += `}\n`;

if (darkVars.length) {
  const decls = (indent) =>
    darkVars.map((v) => `${indent}--${v.name}: ${v.dark};\n`).join("");

  css +=
    `\n/* ============ Dark theme ============\n` +
    `   ${darkVars.length} semantic tokens re-alias; the raw ramps never move.\n` +
    `   Followed automatically unless the visitor has pinned light. */\n` +
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n` +
    decls("    ") +
    `  }\n}\n` +
    `\n/* Pinned by the visitor — wins over the OS preference either way. */\n` +
    `:root[data-theme="dark"] {\n` +
    decls("  ") +
    `}\n`;
}

/* Paper is a third theme, and it must beat the other two — hence last.
   Screen themes are a preference; print is a physical constraint (no
   backlight, ink costs money, greyscale is likely), so a visitor reading
   in dark still gets ink-on-paper when they hit print. */
if (printVars.length) {
  css +=
    `\n/* ============ Print ============\n` +
    `   ${printVars.length} tokens re-alias for paper. Emitted after the dark\n` +
    `   blocks so it wins regardless of the theme on screen. */\n` +
    `@media print {\n  :root, :root[data-theme="dark"], :root[data-theme="light"] {\n` +
    printVars.map((v) => `    --${v.name}: ${v.print};\n`).join("") +
    `  }\n}\n`;
}

/* ---------- dist/tokens.flat.json (aliases resolved) ----------
   Resolved twice, through a light and a dark alias map. A token with no
   `dark` of its own can still land on a different colour in dark mode by
   pointing at one that does (content-primary → primary), so darkResolved is
   computed for every token and emitted whenever it actually differs. That is
   what makes this file enough on its own for the Figma push and for agents. */
const byName = new Map();
const byNameDark = new Map();
const byNamePrint = new Map();
for (const { vars } of categories) {
  for (const v of vars) {
    byName.set(v.name, v.value);
    byNameDark.set(v.name, v.dark ?? v.value);
    byNamePrint.set(v.name, v.print ?? v.value);
  }
}

function resolveWith(map, value, seen = new Set()) {
  return value.replace(/var\(--([a-z0-9-]+)\)/gi, (m, name) => {
    if (seen.has(name) || !map.has(name)) return m;
    seen.add(name);
    return resolveWith(map, map.get(name), seen);
  });
}
const resolve = (value) => resolveWith(byName, value);
const resolveDark = (value) => resolveWith(byNameDark, value);
const resolvePrint = (value) => resolveWith(byNamePrint, value);

const flat = {};
for (const { cat, vars } of categories) {
  for (const v of vars) {
    const resolved = resolve(v.value);
    const darkResolved = resolveDark(v.dark ?? v.value);
    const printResolved = resolvePrint(v.print ?? v.value);
    flat[`${cat}.${v.name}`] = {
      cssVar: `--${v.name}`,
      value: v.value,
      ...(resolved !== v.value ? { resolved } : {}),
      ...(v.dark !== undefined ? { dark: v.dark } : {}),
      ...(darkResolved !== resolved ? { darkResolved } : {}),
      ...(v.print !== undefined ? { print: v.print } : {}),
      ...(printResolved !== resolved ? { printResolved } : {}),
      ...(v.description ? { description: v.description } : {}),
    };
  }
}

mkdirSync(join(root, "dist"), { recursive: true });
writeFileSync(join(root, "dist", "tokens.css"), css);
writeFileSync(join(root, "dist", "tokens.flat.json"), JSON.stringify(flat, null, 2) + "\n");
console.log(`✓ dist/tokens.css        (${categories.reduce((n, c) => n + c.vars.length, 0)} variables, ${darkVars.length} dark, ${printVars.length} print)`);
console.log(`✓ dist/tokens.flat.json  (${Object.keys(flat).length} entries)`);

/* ---------- ../content/system.generated.json ----------
   The system's statistics, emitted rather than asserted. The site and the CV
   advertise these numbers in prose; build-content.mjs interpolates them from
   here, so a token or a component landing updates every sentence that quotes
   it. The counts gate below then only has to catch a hand-edit of a generated
   file — it can no longer be the thing that keeps the numbers honest, because
   nothing types them by hand any more. */
const compDir = join(root, "components");
const storyDir = join(root, "stories");
const components = existsSync(compDir)
  ? readdirSync(compDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name)
  : [];
const tokenCount = categories.reduce((n, c) => n + c.vars.length, 0);
const valueCount = tokenCount + darkVars.length + printVars.length;

mkdirSync(join(root, "..", "content"), { recursive: true });
writeFileSync(
  join(root, "..", "content", "system.generated.json"),
  JSON.stringify(
    {
      $generatedBy: "design-system/scripts/build.mjs — do not edit",
      tokens: tokenCount,
      values: valueCount,
      light: tokenCount,
      dark: darkVars.length,
      print: printVars.length,
      components: components.length,
      componentNames: components,
    },
    null,
    2
  ) + "\n"
);
console.log(`✓ ../content/system.generated.json (${tokenCount} tokens, ${valueCount} values, ${components.length} components)`);

/* ============================================================
   The component tier — derived contract + spec cross-check.

   The token tier above is generated, so a claim about a token cannot be
   true and unenforced at the same time. Everything below exists because
   the component tier had no such property: `spec.md` was hand-typed prose
   that nothing verified, and four classes named in canonical HTML that
   agents are told to copy verbatim had no CSS rule anywhere.

   Two tiers, deliberately:

     DERIVED — selectors, elements, variants and the consumed token set,
     read straight out of css/components.css. Emitted as
     dist/components.json, the machine-readable counterpart to
     dist/tokens.flat.json.

     DECLARED — the residue a parser cannot reach: which component a CSS
     block belongs to (`@component` on the banner), and each spec's JSON
     frontmatter (id / status / since / a11y). Hand-written, and therefore
     drift-tested below rather than trusted.

   What is NOT generated: the prose. The a11y rationale, the AI notes and
   the `contain: size` feedback-loop explanation in skeleton/spec.md are
   irreducible judgement and stay in spec.md where a human wrote them.
   ============================================================ */

const STATUSES = ["stable", "experimental", "deprecated"];
/* `since` names the BUILD-LOG.md phase a component first shipped in.
   "initial" is the design system that predates the content pipeline
   ("What existed before"). Anything else must be a phase recorded there. */
const PHASES = ["initial", "phase-0", "phase-1", "phase-2", "phase-3"];

const stripComments = (s) => s.replace(/\/\*[\s\S]*?\*\//g, "");
const uniq = (a) => [...new Set(a)].sort();

/* ---------- components.css → banner-delimited blocks ----------
   The file is banner-organised, and each banner's first line carries
   `@component <id>` — the one fact about this file no parser can derive
   ("Row — definition (skills)" is the `row` component; "Facts" is `fact`).
   `@component none` marks a block that belongs to no single component
   (the foundation reset, the reduced-motion block). */
const componentsCssPath = join(root, "css", "components.css");
const componentsCss = readFileSync(componentsCssPath, "utf8");

const BANNER = /^\/\* =+ (.+?) =+ @component (\S+)/gm;
const blocks = [];
{
  const marks = [];
  for (const m of componentsCss.matchAll(BANNER)) {
    marks.push({ title: m[1].trim(), owner: m[2], start: m.index });
  }
  marks.forEach((mk, i) => {
    const end = i + 1 < marks.length ? marks[i + 1].start : componentsCss.length;
    blocks.push({ ...mk, body: componentsCss.slice(mk.start, end) });
  });
}

/* Selector preludes, brace-walked rather than regexed: a regex cannot tell
   `@media (…) {` from a rule, and would happily report `50%` inside
   @keyframes as a selector. */
function selectorsIn(text) {
  const src = stripComments(text);
  const out = [];
  const stack = [];
  let buf = "";
  for (const ch of src) {
    if (ch === "{") {
      const prelude = buf.trim();
      buf = "";
      if (prelude.startsWith("@")) {
        stack.push(prelude.startsWith("@keyframes") ? "keyframes" : "at");
      } else {
        if (stack[stack.length - 1] !== "keyframes") {
          prelude.split(",").forEach((s) => s.trim() && out.push(s.trim().replace(/\s+/g, " ")));
        }
        stack.push("rule");
      }
    } else if (ch === "}") {
      stack.pop();
      buf = "";
    } else {
      buf += ch;
    }
  }
  return out;
}

const CLASS_IN_SELECTOR = /\.(-?[_a-zA-Z][\w-]*)/g;
const VAR_USE = /var\(\s*(--[a-z0-9-]+)/gi;

for (const b of blocks) {
  b.selectors = selectorsIn(b.body);
  b.classes = uniq(b.selectors.flatMap((s) => [...s.matchAll(CLASS_IN_SELECTOR)].map((m) => "." + m[1])));
  b.tokens = uniq([...stripComments(b.body).matchAll(VAR_USE)].map((m) => m[1]));
}

/** Every class with at least one rule anywhere in components.css. */
const definedClasses = new Set(blocks.flatMap((b) => b.classes));

/** What the foundation blocks apply to everything (`body`, `.mono`, the focus ring). */
const foundationTokens = new Set(blocks.filter((b) => b.owner === "none").flatMap((b) => b.tokens));

/* ---------- spec.md → frontmatter + claimed classes + declared tokens ----------
   "Claimed" is exactly what design-system/README.md tells an agent to copy:
   the class attributes of the canonical HTML, plus any `.class` written in
   backticks in the prose. The negative lookbehind is what keeps `main.js`,
   `tokens.json` and `0.78rem` out of the class list. */
const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---\r?\n/;
const HTML_FENCE = /```html\r?\n([\s\S]*?)```/g;
const CLASS_ATTR = /class="([^"]*)"/g;
const BACKTICKED = /`([^`\n]+)`/g;
const CLASS_IN_PROSE = /(?<![\w.])\.([a-z][a-z0-9_-]*)/g;

function readSpec(id) {
  const path = join(compDir, id, "spec.md");
  const text = readFileSync(path, "utf8");

  let front = null;
  let frontError = null;
  const fm = text.match(FRONTMATTER);
  if (fm) {
    try {
      front = JSON.parse(fm[1]);
    } catch (e) {
      frontError = e.message;
    }
  }

  const claimed = new Set();
  for (const fence of text.matchAll(HTML_FENCE)) {
    for (const attr of fence[1].matchAll(CLASS_ATTR)) {
      attr[1].split(/\s+/).forEach((c) => c && claimed.add("." + c));
    }
  }
  for (const span of text.matchAll(BACKTICKED)) {
    for (const m of span[1].matchAll(CLASS_IN_PROSE)) claimed.add("." + m[1]);
  }

  /* Only a backticked span that is EXACTLY a token counts as a declaration.
     A bare regex for `--x` also matches the modifier half of `.sec--tint`,
     which would report `--tint` as an undeclared token forever. */
  const tokenSection = (text.split(/^## +Tokens *$/m)[1] ?? "").split(/^## /m)[0];
  const declaredTokens = uniq(
    [...tokenSection.matchAll(BACKTICKED)].map((m) => m[1]).filter((s) => /^--[a-z0-9-]+$/.test(s))
  );

  return { path, text, front, frontError, claimed: [...claimed].sort(), declaredTokens };
}

const specs = Object.fromEntries(components.map((id) => [id, readSpec(id)]));

/* ---------- dist/components.json ----------
   The derived contract dist/tokens.flat.json has had all along and the
   component tier has not: what an agent may branch on instead of parsing
   19 markdown files of inconsistent shape. */
const owned = (id) => blocks.filter((b) => b.owner === id);
const suffixes = (classes, sep) =>
  uniq(
    classes
      .map((c) => {
        const i = c.indexOf(sep, 1);
        return i === -1 ? null : c.slice(i);
      })
      .filter(Boolean)
  );

const componentContract = components.map((id) => {
  const mine = owned(id);
  const classes = uniq(mine.flatMap((b) => b.classes));
  const s = specs[id];
  return {
    id,
    status: s.front?.status ?? null,
    since: s.front?.since ?? null,
    a11y: s.front?.a11y ?? null,
    spec: `components/${id}/spec.md`,
    story: `stories/${id}.stories.js`,
    blocks: mine.map((b) => b.title),
    classes,
    elements: suffixes(classes, "__"),
    variants: suffixes(classes, "--"),
    selectors: uniq(mine.flatMap((b) => b.selectors)),
    tokens: uniq(mine.flatMap((b) => b.tokens)),
  };
});

writeFileSync(
  join(root, "dist", "components.json"),
  JSON.stringify(
    {
      $generatedBy: "design-system/scripts/build.mjs — do not edit",
      $doc:
        "Derived component contract. selectors/classes/elements/variants/tokens are parsed out of css/components.css and are true by construction. status/since/a11y are DECLARED in each spec.md's JSON frontmatter and drift-tested by `build.mjs --check`. The prose — a11y rationale, AI notes, the contain:size explanation — is deliberately not here; it lives in spec.md because it is judgement, not fact.",
      $derivedFrom: ["css/components.css", "components/*/spec.md (frontmatter only)"],
      count: componentContract.length,
      components: componentContract,
    },
    null,
    2
  ) + "\n"
);
console.log(
  `✓ dist/components.json   (${componentContract.length} components, ` +
    `${uniq(componentContract.flatMap((c) => c.classes)).length} classes, ` +
    `${blocks.length} css blocks)`
);

/* ---------- coverage gate: every component = spec.md + story ---------- */
if (CHECK) {
  const problems = [];
  for (const c of components) {
    if (!existsSync(join(compDir, c, "spec.md"))) problems.push(`components/${c}/ has no spec.md`);
    if (!existsSync(join(storyDir, `${c}.stories.js`))) problems.push(`components/${c}/ has no stories/${c}.stories.js`);
  }
  if (problems.length) {
    console.error(`✗ coverage check failed:\n  - ${problems.join("\n  - ")}`);
    process.exit(1);
  }
  console.log(`✓ coverage check         (${components.length} components, each with spec.md + story)`);

  /* ---------- counts gate: the generated prose must still quote the truth ----------
     These figures are a claim the site makes about itself. They are no longer
     typed by hand — build-content.mjs interpolates them from
     content/system.generated.json — so this is no longer the mechanism that
     keeps them true. It is the guard against someone hand-editing a generated
     file, which is the one way drift can still get in. Positive assertions, not
     a scan: each file must contain the current number, which is unambiguous and
     cannot false-positive on unrelated figures in the prose.

     A missing file is a FAILURE, not a pass. The old `existsSync → continue`
     meant relocating content silently disabled the check. */
  const advertised = [
    ["../README.md", [`${tokenCount} tokens`, `${valueCount} values`, `${components.length} components`]],
    ["../cv.html", [`${tokenCount} tokens`, `${valueCount} values`, `${components.length} components`]],
    ["../js/case-studies.js", [`${tokenCount} tokens`, `${valueCount} values`, `${components.length} components`]],
  ];
  const stale = [];
  // Prose wraps: "106\n  values" is the same claim as "106 values", so match on
  // whitespace-collapsed text rather than forcing docs to avoid line breaks.
  const flatten = (s) => s.replace(/\s+/g, " ");
  for (const [rel, needles] of advertised) {
    const path = join(root, rel);
    if (!existsSync(path)) {
      stale.push(`${rel} is missing — it advertises the counts and must exist`);
      continue;
    }
    const text = flatten(readFileSync(path, "utf8"));
    for (const needle of needles) {
      if (!text.includes(needle)) stale.push(`${rel} does not say "${needle}"`);
    }
  }
  if (stale.length) {
    console.error(
      `✗ counts check failed — the docs advertise numbers that are no longer true:\n  - ${stale.join("\n  - ")}\n` +
        `  Current: ${tokenCount} tokens, ${valueCount} values (${tokenCount} light + ${darkVars.length} dark + ${printVars.length} print), ${components.length} components.\n` +
        `  cv.html and js/case-studies.js are GENERATED — do not edit them. Run:\n` +
        `    node design-system/scripts/build.mjs && node scripts/build-content.mjs`
    );
    process.exit(1);
  }
  console.log(`✓ counts check           (${tokenCount} tokens, ${valueCount} values, ${components.length} components — as advertised)`);

  /* ---------- contract gate: spec.md must be TRUE, not merely present ----------
     The coverage gate above checks that a spec and a story EXIST. It never
     checked that they were true, and they were not: four classes named in
     canonical HTML had no rule anywhere, and several `## Tokens` lists had
     drifted from the CSS beside them. design-system/README.md tells agents
     the canonical HTML "is not an example — it is THE pattern. Copy it," so
     a class named there that means nothing is a defect, not a nit.

     Three assertions, in the order a failure is easiest to act on:
       1. the `@component` markers are complete and resolve  (DECLARED tier)
       2. every spec carries valid JSON frontmatter           (DECLARED tier)
       3. spec ↔ CSS agree on classes and tokens             (the cross-check)

     Direction matters on tokens. Consumed-but-undeclared is a FAILURE: the
     spec is lying about what the component costs. Declared-but-unconsumed is
     a WARNING only, because a component can legitimately name a token it gets
     through a utility class in its markup (`source` wears `--font-mono` via
     `.mono`) rather than through its own block. */
  const broken = [];
  const warnings = [];

  /* 1. @component markers */
  const bannerCount = (componentsCss.match(/^\/\* =+ .+? =+/gm) ?? []).length;
  if (bannerCount !== blocks.length) {
    broken.push(
      `css/components.css: ${bannerCount - blocks.length} banner(s) carry no \`@component <id>\` marker. ` +
        `Every banner needs one; use \`@component none\` for a block that belongs to no single component.`
    );
  }
  const knownOwners = new Set([...components, "none"]);
  for (const b of blocks) {
    if (!knownOwners.has(b.owner)) {
      broken.push(`css/components.css: block "${b.title}" is marked \`@component ${b.owner}\`, which is not a directory under components/`);
    }
  }
  for (const id of components) {
    if (!owned(id).length) broken.push(`components/${id}/ is claimed by no CSS block — no banner in components.css says \`@component ${id}\``);
  }

  /* 2. spec frontmatter */
  for (const id of components) {
    const s = specs[id];
    const where = `components/${id}/spec.md`;
    if (s.frontError) { broken.push(`${where}: frontmatter is not valid JSON — ${s.frontError}`); continue; }
    if (!s.front) { broken.push(`${where}: no JSON frontmatter. Needs a \`---\` block with { id, status, since, a11y }, matching the content/*.md convention.`); continue; }
    if (s.front.id !== id) broken.push(`${where}: frontmatter id is "${s.front.id}", directory is "${id}"`);
    if (!STATUSES.includes(s.front.status)) broken.push(`${where}: status "${s.front.status}" is not one of ${STATUSES.join(" | ")}`);
    if (!PHASES.includes(s.front.since)) broken.push(`${where}: since "${s.front.since}" is not one of ${PHASES.join(" | ")}`);
    if (typeof s.front.a11y !== "string" || !s.front.a11y.trim()) broken.push(`${where}: a11y must be a non-empty one-line string`);
  }

  /* 3. the cross-check */
  for (const id of components) {
    const s = specs[id];
    const where = `components/${id}/spec.md`;

    for (const cls of s.claimed) {
      if (!definedClasses.has(cls)) {
        broken.push(`${where} claims \`${cls}\` but no rule in css/components.css defines it — define the rule or drop the class from the spec`);
      }
    }

    const consumed = uniq(owned(id).flatMap((b) => b.tokens));
    const declared = new Set(s.declaredTokens);
    for (const t of consumed) {
      if (!declared.has(t)) broken.push(`${where}: its CSS consumes \`${t}\` and the \`## Tokens\` list omits it`);
    }
    /* A component may legitimately name a token it inherits from the
       foundation rather than sets itself — `source` wears `--font-mono`
       through the `.mono` utility, `typography` documents `--font-body`
       which `body` applies. Those are not drift. A token in neither its own
       block nor the foundation is. */
    for (const t of s.declaredTokens) {
      if (!consumed.includes(t) && !foundationTokens.has(t)) {
        warnings.push(`${where}: \`## Tokens\` lists \`${t}\`, which neither its own CSS block nor the foundation consumes`);
      }
    }
  }

  if (broken.length) {
    console.error(`✗ contract check failed — spec.md and components.css disagree:\n  - ${broken.join("\n  - ")}`);
    process.exit(1);
  }
  if (warnings.length) {
    console.warn(`! contract warnings (not fatal):\n  - ${warnings.join("\n  - ")}`);
  }
  const claimedTotal = components.reduce((n, id) => n + specs[id].claimed.length, 0);
  console.log(`✓ contract check         (${claimedTotal} spec-claimed classes all defined, ${blocks.length} css blocks owned, token lists match)`);
}
