#!/usr/bin/env node
/* ============================================================
   Design system build — zero dependencies.

   tokens/tokens.json  →  dist/tokens.css       (:root custom properties,
                                                 consumed by the site + Storybook)
                       →  dist/tokens.flat.json (dotted keys with resolved
                                                 values, consumed by AI agents
                                                 and the Figma push procedure)
                       →  ../content/system.generated.json
                                                 (the system's own statistics,
                                                 consumed by scripts/build-content.mjs
                                                 so the prose that advertises them
                                                 has exactly one source)

   `node scripts/build.mjs`          build tokens + system stats
   `node scripts/build.mjs --check`  build + verify every component has
                                     spec.md and a story (coverage gate), and
                                     that the generated prose still quotes the
                                     current numbers (counts gate)

   Run order for the repo as a whole: this script first (it emits the stats),
   then `node scripts/build-content.mjs` from the repo root (it consumes them).
   ============================================================ */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const tokens = JSON.parse(readFileSync(join(root, "tokens", "tokens.json"), "utf8"));

/* ---------- normalize: every entry -> { value, dark?, print?, description? } ---------- */
const categories = [];
for (const [cat, entries] of Object.entries(tokens)) {
  if (cat.startsWith("$")) continue;
  const doc = entries.$doc ?? "";
  const vars = [];
  for (const [name, raw] of Object.entries(entries)) {
    if (name.startsWith("$")) continue;
    const { value, dark, print, description } =
      typeof raw === "string"
        ? { value: raw, dark: undefined, print: undefined, description: undefined }
        : raw;
    vars.push({ name, value, dark, print, description });
  }
  categories.push({ cat, doc, vars });
}

/* ---------- dist/tokens.css ----------
   Three blocks. :root carries the light theme and every theme-independent
   token. The dark overrides are emitted twice from the same source: once
   behind the OS preference (skipped when the visitor has pinned light) and
   once behind an explicit data-theme, so the control can override the OS in
   either direction. Anything without a `dark` value simply cascades. */
const pick = (key) =>
  categories.flatMap(({ cat, vars }) =>
    vars.filter((v) => v[key] !== undefined).map((v) => ({ ...v, cat }))
  );
const darkVars = pick("dark");
const printVars = pick("print");

let css = `/* GENERATED by scripts/build.mjs from tokens/tokens.json — do not edit.
   Edit tokens/tokens.json and run \`npm run build\`. */\n:root {\n`;
for (const { doc, vars } of categories) {
  if (doc) css += `\n  /* --- ${doc} --- */\n`;
  for (const v of vars) {
    css += `  --${v.name}: ${v.value};${v.description ? ` /* ${v.description} */` : ""}\n`;
  }
}
css += `}\n`;

if (darkVars.length) {
  const decls = (indent) =>
    darkVars.map((v) => `${indent}--${v.name}: ${v.dark};\n`).join("");

  css +=
    `\n/* ============ Dark theme ============\n` +
    `   ${darkVars.length} semantic tokens re-alias; the raw ramps never move.\n` +
    `   Followed automatically unless the visitor has pinned light. */\n` +
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n` +
    decls("    ") +
    `  }\n}\n` +
    `\n/* Pinned by the visitor — wins over the OS preference either way. */\n` +
    `:root[data-theme="dark"] {\n` +
    decls("  ") +
    `}\n`;
}

/* Paper is a third theme, and it must beat the other two — hence last.
   Screen themes are a preference; print is a physical constraint (no
   backlight, ink costs money, greyscale is likely), so a visitor reading
   in dark still gets ink-on-paper when they hit print. */
if (printVars.length) {
  css +=
    `\n/* ============ Print ============\n` +
    `   ${printVars.length} tokens re-alias for paper. Emitted after the dark\n` +
    `   blocks so it wins regardless of the theme on screen. */\n` +
    `@media print {\n  :root, :root[data-theme="dark"], :root[data-theme="light"] {\n` +
    printVars.map((v) => `    --${v.name}: ${v.print};\n`).join("") +
    `  }\n}\n`;
}

/* ---------- dist/tokens.flat.json (aliases resolved) ----------
   Resolved twice, through a light and a dark alias map. A token with no
   `dark` of its own can still land on a different colour in dark mode by
   pointing at one that does (content-primary → primary), so darkResolved is
   computed for every token and emitted whenever it actually differs. That is
   what makes this file enough on its own for the Figma push and for agents. */
const byName = new Map();
const byNameDark = new Map();
const byNamePrint = new Map();
for (const { vars } of categories) {
  for (const v of vars) {
    byName.set(v.name, v.value);
    byNameDark.set(v.name, v.dark ?? v.value);
    byNamePrint.set(v.name, v.print ?? v.value);
  }
}

function resolveWith(map, value, seen = new Set()) {
  return value.replace(/var\(--([a-z0-9-]+)\)/gi, (m, name) => {
    if (seen.has(name) || !map.has(name)) return m;
    seen.add(name);
    return resolveWith(map, map.get(name), seen);
  });
}
const resolve = (value) => resolveWith(byName, value);
const resolveDark = (value) => resolveWith(byNameDark, value);
const resolvePrint = (value) => resolveWith(byNamePrint, value);

const flat = {};
for (const { cat, vars } of categories) {
  for (const v of vars) {
    const resolved = resolve(v.value);
    const darkResolved = resolveDark(v.dark ?? v.value);
    const printResolved = resolvePrint(v.print ?? v.value);
    flat[`${cat}.${v.name}`] = {
      cssVar: `--${v.name}`,
      value: v.value,
      ...(resolved !== v.value ? { resolved } : {}),
      ...(v.dark !== undefined ? { dark: v.dark } : {}),
      ...(darkResolved !== resolved ? { darkResolved } : {}),
      ...(v.print !== undefined ? { print: v.print } : {}),
      ...(printResolved !== resolved ? { printResolved } : {}),
      ...(v.description ? { description: v.description } : {}),
    };
  }
}

mkdirSync(join(root, "dist"), { recursive: true });
writeFileSync(join(root, "dist", "tokens.css"), css);
writeFileSync(join(root, "dist", "tokens.flat.json"), JSON.stringify(flat, null, 2) + "\n");
console.log(`✓ dist/tokens.css        (${categories.reduce((n, c) => n + c.vars.length, 0)} variables, ${darkVars.length} dark, ${printVars.length} print)`);
console.log(`✓ dist/tokens.flat.json  (${Object.keys(flat).length} entries)`);

/* ---------- ../content/system.generated.json ----------
   The system's statistics, emitted rather than asserted. The site and the CV
   advertise these numbers in prose; build-content.mjs interpolates them from
   here, so a token or a component landing updates every sentence that quotes
   it. The counts gate below then only has to catch a hand-edit of a generated
   file — it can no longer be the thing that keeps the numbers honest, because
   nothing types them by hand any more. */
const compDir = join(root, "components");
const storyDir = join(root, "stories");
const components = existsSync(compDir)
  ? readdirSync(compDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name)
  : [];
const tokenCount = categories.reduce((n, c) => n + c.vars.length, 0);
const valueCount = tokenCount + darkVars.length + printVars.length;

mkdirSync(join(root, "..", "content"), { recursive: true });
writeFileSync(
  join(root, "..", "content", "system.generated.json"),
  JSON.stringify(
    {
      $generatedBy: "design-system/scripts/build.mjs — do not edit",
      tokens: tokenCount,
      values: valueCount,
      light: tokenCount,
      dark: darkVars.length,
      print: printVars.length,
      components: components.length,
      componentNames: components,
    },
    null,
    2
  ) + "\n"
);
console.log(`✓ ../content/system.generated.json (${tokenCount} tokens, ${valueCount} values, ${components.length} components)`);

/* ---------- coverage gate: every component = spec.md + story ---------- */
if (CHECK) {
  const problems = [];
  for (const c of components) {
    if (!existsSync(join(compDir, c, "spec.md"))) problems.push(`components/${c}/ has no spec.md`);
    if (!existsSync(join(storyDir, `${c}.stories.js`))) problems.push(`components/${c}/ has no stories/${c}.stories.js`);
  }
  if (problems.length) {
    console.error(`✗ coverage check failed:\n  - ${problems.join("\n  - ")}`);
    process.exit(1);
  }
  console.log(`✓ coverage check         (${components.length} components, each with spec.md + story)`);

  /* ---------- counts gate: the generated prose must still quote the truth ----------
     These figures are a claim the site makes about itself. They are no longer
     typed by hand — build-content.mjs interpolates them from
     content/system.generated.json — so this is no longer the mechanism that
     keeps them true. It is the guard against someone hand-editing a generated
     file, which is the one way drift can still get in. Positive assertions, not
     a scan: each file must contain the current number, which is unambiguous and
     cannot false-positive on unrelated figures in the prose.

     A missing file is a FAILURE, not a pass. The old `existsSync → continue`
     meant relocating content silently disabled the check. */
  const advertised = [
    ["../README.md", [`${tokenCount} tokens`, `${valueCount} values`, `${components.length} components`]],
    ["../cv.html", [`${tokenCount} tokens`, `${valueCount} values`, `${components.length} components`]],
    ["../js/case-studies.js", [`${tokenCount} tokens`, `${valueCount} values`, `${components.length} components`]],
  ];
  const stale = [];
  // Prose wraps: "106\n  values" is the same claim as "106 values", so match on
  // whitespace-collapsed text rather than forcing docs to avoid line breaks.
  const flatten = (s) => s.replace(/\s+/g, " ");
  for (const [rel, needles] of advertised) {
    const path = join(root, rel);
    if (!existsSync(path)) {
      stale.push(`${rel} is missing — it advertises the counts and must exist`);
      continue;
    }
    const text = flatten(readFileSync(path, "utf8"));
    for (const needle of needles) {
      if (!text.includes(needle)) stale.push(`${rel} does not say "${needle}"`);
    }
  }
  if (stale.length) {
    console.error(
      `✗ counts check failed — the docs advertise numbers that are no longer true:\n  - ${stale.join("\n  - ")}\n` +
        `  Current: ${tokenCount} tokens, ${valueCount} values (${tokenCount} light + ${darkVars.length} dark + ${printVars.length} print), ${components.length} components.\n` +
        `  cv.html and js/case-studies.js are GENERATED — do not edit them. Run:\n` +
        `    node design-system/scripts/build.mjs && node scripts/build-content.mjs`
    );
    process.exit(1);
  }
  console.log(`✓ counts check           (${tokenCount} tokens, ${valueCount} values, ${components.length} components — as advertised)`);
}
