#!/usr/bin/env node
/* ============================================================
   Design system build — zero dependencies.

   tokens/tokens.json  →  dist/tokens.css       (:root custom properties,
                                                 consumed by the site + Storybook)
                       →  dist/tokens.flat.json (dotted keys with resolved
                                                 values, consumed by AI agents
                                                 and the Figma push procedure)

   `node scripts/build.mjs`          build tokens
   `node scripts/build.mjs --check`  build + verify every component has
                                     spec.md and a story (coverage gate)
   ============================================================ */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const tokens = JSON.parse(readFileSync(join(root, "tokens", "tokens.json"), "utf8"));

/* ---------- normalize: every entry -> { value, description? } ---------- */
const categories = [];
for (const [cat, entries] of Object.entries(tokens)) {
  if (cat.startsWith("$")) continue;
  const doc = entries.$doc ?? "";
  const vars = [];
  for (const [name, raw] of Object.entries(entries)) {
    if (name.startsWith("$")) continue;
    const { value, description } =
      typeof raw === "string" ? { value: raw, description: undefined } : raw;
    vars.push({ name, value, description });
  }
  categories.push({ cat, doc, vars });
}

/* ---------- dist/tokens.css ---------- */
let css = `/* GENERATED by scripts/build.mjs from tokens/tokens.json — do not edit.
   Edit tokens/tokens.json and run \`npm run build\`. */\n:root {\n`;
for (const { doc, vars } of categories) {
  if (doc) css += `\n  /* --- ${doc} --- */\n`;
  for (const v of vars) {
    css += `  --${v.name}: ${v.value};${v.description ? ` /* ${v.description} */` : ""}\n`;
  }
}
css += `}\n`;

/* ---------- dist/tokens.flat.json (aliases resolved) ---------- */
const byName = new Map();
for (const { vars } of categories) for (const v of vars) byName.set(v.name, v.value);

function resolve(value, seen = new Set()) {
  return value.replace(/var\(--([a-z0-9-]+)\)/gi, (m, name) => {
    if (seen.has(name) || !byName.has(name)) return m;
    seen.add(name);
    return resolve(byName.get(name), seen);
  });
}

const flat = {};
for (const { cat, vars } of categories) {
  for (const v of vars) {
    const resolved = resolve(v.value);
    flat[`${cat}.${v.name}`] = {
      cssVar: `--${v.name}`,
      value: v.value,
      ...(resolved !== v.value ? { resolved } : {}),
      ...(v.description ? { description: v.description } : {}),
    };
  }
}

mkdirSync(join(root, "dist"), { recursive: true });
writeFileSync(join(root, "dist", "tokens.css"), css);
writeFileSync(join(root, "dist", "tokens.flat.json"), JSON.stringify(flat, null, 2) + "\n");
console.log(`✓ dist/tokens.css        (${categories.reduce((n, c) => n + c.vars.length, 0)} variables)`);
console.log(`✓ dist/tokens.flat.json  (${Object.keys(flat).length} entries)`);

/* ---------- coverage gate: every component = spec.md + story ---------- */
if (CHECK) {
  const compDir = join(root, "components");
  const storyDir = join(root, "stories");
  const problems = [];
  const components = existsSync(compDir)
    ? readdirSync(compDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name)
    : [];
  for (const c of components) {
    if (!existsSync(join(compDir, c, "spec.md"))) problems.push(`components/${c}/ has no spec.md`);
    if (!existsSync(join(storyDir, `${c}.stories.js`))) problems.push(`components/${c}/ has no stories/${c}.stories.js`);
  }
  if (problems.length) {
    console.error(`✗ coverage check failed:\n  - ${problems.join("\n  - ")}`);
    process.exit(1);
  }
  console.log(`✓ coverage check         (${components.length} components, each with spec.md + story)`);
}
