#!/usr/bin/env node
/* ============================================================
   Content build — zero dependencies.

   content/                →  js/case-studies.js        (window.CASE_STUDIES)
     profile.json             index.html regions        (<!-- content:NAME -->)
     capabilities.json        cv.html regions
     skills.json              content/dist/content.json (retrieval index)
     education.json           content/dist/site.jsonld  (schema.org)
     facts.json               llms.txt                  (agent-readable summary)
     evals.json
     projects/*.md
     experience/*.md
     assets/pipeline.svg
     system.generated.json         ← emitted by design-system/scripts/build.mjs
   design-system/dist/components.json  ← same, folded in verbatim

   `node scripts/build-content.mjs`          write every artefact
   `node scripts/build-content.mjs --check`  regenerate into memory and fail if
                                             anything on disk is stale (CI gate)

   Run order: `design-system/scripts/build.mjs` first — it emits
   content/system.generated.json and dist/components.json, which this build
   interpolates and folds in — then this.

   THE COUNTS DO NOT REACH THE CORPUS. Everything the design system emits is
   rendered into pages and into non-chunk fields of content.json, and is elided
   from chunk text. scripts/build-vectors.mjs fingerprints the corpus as a hash
   over chunk heading+text, so this is what stops a token or component landing
   from invalidating a billed embedding cache and moving the eval baseline. See
   `elideStats` below, and the `designSystem` key in buildContentJson.

   The one rule: prose is moved, never rewritten. Every string this script
   emits was authored in content/ and is reproduced verbatim. If a sentence
   reads awkwardly, it ships awkward; the point of the pipeline is that a claim
   about this person is traceable to something he actually wrote.
   ============================================================ */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const read = (...p) => readFileSync(join(root, ...p), "utf8");
const readJSON = (...p) => JSON.parse(read(...p));

/* Generated bytes must not depend on the OS that produced them: everything is
   written LF and every comparison normalises first. See .gitattributes. */
const lf = (s) => s.replace(/\r\n/g, "\n");

/* ============================================================
   1. Load
   ============================================================ */

/* Both of these are emitted by design-system/scripts/build.mjs. Neither is ever
   hand-edited, and this build cannot run without them — which is the whole
   reason the run order is "design system, then content". */
for (const artefact of [
  ["content", "system.generated.json"],
  ["design-system", "dist", "components.json"],
]) {
  if (existsSync(join(root, ...artefact))) continue;
  console.error(
    `✗ ${artefact.join("/")} is missing.\n` +
      `  It is emitted by the design system build. Run:\n` +
      `    node design-system/scripts/build.mjs`
  );
  process.exit(1);
}

const system = readJSON("content", "system.generated.json");

/* The component contract, folded in so lib/knowledge has ONE artefact to read.
   Boundary note: this is the design system's PUBLISHED dist/, not its internals
   (scripts/check-boundaries.mjs guards design-system/{tokens,components,stories,
   scripts,figma}/), and it enters the graph the same way the token counts do —
   through the content build, never by a consumer reaching sideways into
   design-system/dist/ for itself. */
const dsComponents = readJSON("design-system", "dist", "components.json");
const profile = readJSON("content", "profile.json");
const capabilities = readJSON("content", "capabilities.json");
const skills = readJSON("content", "skills.json");
const education = readJSON("content", "education.json");
const facts = readJSON("content", "facts.json");
const evalsPage = readJSON("content", "evals.json");
const pipelineSvg = lf(read("content", "assets", "pipeline.svg")).trimEnd();

/* The system's own statistics are interpolated into the prose that advertises
   them, so the numbers have exactly one source and drift is structural rather
   than editorial. `{{tokens}}` etc. are substituted before any markdown runs. */
const STATS = {
  tokens: String(system.tokens),
  values: String(system.values),
  components: String(system.components),
  /* `dark` was the counter-example that proved the point: the theme count was
     typed as a literal "24" in two places rather than interpolated, so when the
     design system re-aliased its way down to 23 nothing flowed and both the CV
     and the case study shipped a false number. It is a placeholder now. */
  dark: String(system.dark),
};
const STATS_RE = /\{\{(tokens|values|components|dark)\}\}/g;
const stats = (s) => (typeof s === "string" ? s.replace(STATS_RE, (_, k) => STATS[k]) : s);

/* ---------- and the counterpart: the numbers do NOT enter the corpus ----------

   RENDERED surfaces (pages, case studies, llms.txt, the non-chunk fields of
   content.json) get the live figure. The RETRIEVAL CHUNKS get the sentence with
   the figure ELIDED — the placeholder is replaced by nothing and the surrounding
   whitespace collapses, exactly as `plain()` already does to a `{{metric:0}}`
   directive.

   Why: scripts/build-vectors.mjs fingerprints the corpus as
   sha256(`${heading}. ${text}` of every chunk). While the digits sat in chunk
   text, adding one component or renaming one token invalidated the committed
   embedding cache — a billed Voyage rebuild — and moved the eval baseline. A
   pure design-system change reached all the way into the retrieval evaluation.
   Eliding the digits severs that: chunk text is now invariant under a count
   change, so `corpusHash` does not move and the eval numbers stay comparable.

   Why elide rather than leave `{{tokens}}` in place: the placeholder would
   become a BM25 term, would be embedded as noise, and — worse — `search_content`
   hands `chunk.text` to a model, which would then quote "Dark mode is {{dark}}
   tokens" at a reader. Eliding loses only the digit.

   Why nothing is lost by losing the digit: these numbers are structured data,
   not prose. `get_system_facts` returns `content.system` directly and the tool
   description points at it, so "how many tokens?" is answered by the tool layer
   — the same argument /evals already makes for location and availability, which
   are structured fields that deliberately appear in no chunk. */
const elideStats = (s) => (typeof s === "string" ? s.replace(STATS_RE, "") : s);

/* ---------- content files: JSON frontmatter + markdown body ---------- */
function parseEntity(rel) {
  const raw = lf(read(...rel.split("/")));
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) throw new Error(`${rel}: no JSON frontmatter block between --- delimiters`);
  let data;
  try {
    data = JSON.parse(m[1]);
  } catch (e) {
    throw new Error(`${rel}: frontmatter is not valid JSON — ${e.message}`);
  }
  /* No multi-line-string check is needed: JSON forbids a literal newline inside
     a string, so the format enforces "no paragraphs in frontmatter" for free.
     That is the reason the authoring format is JSON rather than a hand-rolled
     Key: Value parser — the constraint is the parser's, not a convention. */
  return { ...data, _file: rel, sections: parseSections(raw.slice(m[0].length), rel) };
}

/* Body = a sequence of `## Free heading text {#kind}` sections. The heading text
   is the author's and is rendered; the slug is the machine classification. */
const KINDS = new Set([
  "summary", "subtitle", "context", "problem", "approach", "system", "outcome", "status",
]);

function parseSections(body, rel) {
  const sections = [];
  const lines = lf(body).split("\n");
  let current = null;
  for (const line of lines) {
    const h = line.match(/^##\s+(.*?)\s*\{#([a-z-]+)\}\s*$/);
    if (h) {
      if (!KINDS.has(h[2])) {
        throw new Error(
          `${rel}: unknown section kind {#${h[2]}} — allowed: ${[...KINDS].join(" | ")}`
        );
      }
      current = { heading: h[1], kind: h[2], blocks: [], _lines: [] };
      sections.push(current);
      continue;
    }
    if (!current) {
      if (line.trim()) throw new Error(`${rel}: content before the first ## heading: "${line.trim()}"`);
      continue;
    }
    current._lines.push(line);
  }
  for (const s of sections) {
    s.blocks = parseBlocks(s._lines);
    delete s._lines;
  }
  return sections;
}

/* Blocks are separated by blank lines. Three kinds:
     - a `{{directive}}` alone on its line
     - a list (every line starts `- `, continuations are indented)
     - a paragraph (soft-wrapped lines join with a single space) */
function parseBlocks(lines) {
  const blocks = [];
  let buf = [];
  const flush = () => {
    if (!buf.length) return;
    const text = buf.join("\n");
    const directive = text.match(/^\{\{([^}]+)\}\}$/);
    if (directive) blocks.push({ type: "directive", value: directive[1] });
    else if (/^-\s/.test(buf[0])) blocks.push({ type: "list", items: splitItems(buf) });
    else blocks.push({ type: "p", text: unwrap(buf) });
    buf = [];
  };
  for (const line of lines) {
    if (!line.trim()) flush();
    else buf.push(line);
  }
  flush();
  return blocks;
}

const unwrap = (lines) => lines.map((l) => l.trim()).join(" ");

function splitItems(lines) {
  const items = [];
  for (const line of lines) {
    if (/^-\s/.test(line)) items.push([line.replace(/^-\s+/, "")]);
    else if (items.length) items[items.length - 1].push(line);
  }
  return items.map(unwrap);
}

const projects = readdirSync(join(root, "content", "projects"))
  .filter((f) => f.endsWith(".md"))
  .map((f) => parseEntity(`content/projects/${f}`));

const experience = readdirSync(join(root, "content", "experience"))
  .filter((f) => f.endsWith(".md"))
  .map((f) => parseEntity(`content/experience/${f}`))
  .sort((a, b) => a.order - b.order);

const caseStudies = projects.filter((p) => p.hasCaseStudy).sort((a, b) => a.index - b.index);
const cardProjects = projects.filter((p) => !p.hasCaseStudy).sort((a, b) => a.order - b.order);

/* ---------- assertions the format promises ---------- */
{
  const problems = [];
  const seen = new Set();
  for (const p of projects) {
    if (seen.has(p.id)) problems.push(`duplicate project id "${p.id}"`);
    seen.add(p.id);
    if (!section(p, "summary")) problems.push(`${p._file}: no {#summary} section`);
    if (p.hasCaseStudy) {
      if (!section(p, "subtitle")) problems.push(`${p._file}: no {#subtitle} section`);
      if (p.accentTag && !p.tags?.includes(p.accentTag)) {
        problems.push(`${p._file}: accentTag "${p.accentTag}" is not a member of tags`);
      }
      if (p.indexAccentTag && !p.indexTags?.includes(p.indexAccentTag)) {
        problems.push(`${p._file}: indexAccentTag "${p.indexAccentTag}" is not in indexTags`);
      }
    }
  }
  for (const e of experience) {
    if (!e.period?.start) problems.push(`${e._file}: period.start is required`);
  }
  if (problems.length) {
    console.error(`✗ content check failed:\n  - ${problems.join("\n  - ")}`);
    process.exit(1);
  }
}

function section(entity, kind) {
  return entity.sections.find((s) => s.kind === kind);
}
function sectionText(entity, kind) {
  const s = section(entity, kind);
  return s ? plain(blocksToText(s.blocks)) : "";
}

/* ============================================================
   2. The markdown subset

   `**bold**` `*em*` `` `code` `` `[text](url)` — everything else is escaped.
   No content file contains raw HTML, so this is the only path from a sentence
   in content/ to a tag on the page.
   ============================================================ */
const escText = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const escAttr = (s) => escText(s).replace(/"/g, "&quot;");

function inline(src) {
  return escText(stats(src))
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, '<a href="$2">$1</a>')
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>");
}

/* Same subset, stripped rather than rendered — this is what the retrieval index
   stores, so a chunk's text reads as the sentence the author typed. */
function plain(src) {
  return stats(src)
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/\{\{[^}]+\}\}/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function blocksToText(blocks) {
  return blocks
    .map((b) => (b.type === "p" ? b.text : b.type === "list" ? b.items.join(" ") : ""))
    .filter(Boolean)
    .join(" ");
}

/* ---------- small emit helpers ---------- */
const pad = (n) => " ".repeat(n);
const indent = (n, lines) => lines.map((l) => (l === "" ? "" : pad(n) + l));
const anchor = (l) =>
  `<a${l.variant === "solid" ? ' class="btn btn--solid"' : l.btn ? ' class="btn"' : ""}` +
  ` href="${escAttr(l.href)}"${l.external ? ' target="_blank" rel="noopener"' : ""}` +
  `${l.style ? ` style="${escAttr(l.style)}"` : ""}>${inline(l.label)}</a>`;

/* ============================================================
   3. Case-study bodies  →  the `content` string in js/case-studies.js

   Rendered at the indentation the template literal already used, so the file
   stays readable in a diff. Blank lines fall before every `<h3>` and before
   every `.ph-grid`, which is the rhythm the hand-written file had.
   ============================================================ */
function mediaBySlot(project, slot) {
  const m = (project.media ?? []).find((x) => x.slot === slot);
  if (!m) throw new Error(`${project._file}: no media slot "${slot}"`);
  return m;
}

const phFigure = (m) =>
  `<figure class="ph"><span class="ph__label">${inline(m.caption)}</span></figure>`;

/* The pipeline diagram is a real file (content/assets/pipeline.svg). The figure
   wrapper's inline style is markup, not content, so it lives here — its
   var(--chrome-border-strong) references are already token-correct and must
   survive verbatim. */
function svgFigure(m) {
  const svg = readFileSync(join(root, "content", "assets", m.src), "utf8");
  return [
    `<figure style="border: 1px solid var(--chrome-border-strong); background: var(--surface-raised); padding: 1.25rem; margin: 1.5rem 0; color: var(--content-primary); max-width: none;">`,
    ...indent(2, lf(svg).trimEnd().split("\n")),
    `  <figcaption class="mono" style="font-size:.68rem;letter-spacing:.08em;text-transform:uppercase;color:var(--chrome-label);margin-top:.75rem">${inline(
      m.caption
    )}</figcaption>`,
    `</figure>`,
  ];
}

function renderDirective(project, value) {
  const [name, arg] = value.split(":");
  if (name === "metric") {
    const metric = project.metrics?.[Number(arg)];
    if (!metric) throw new Error(`${project._file}: {{metric:${arg}}} has no matching metrics entry`);
    return { lines: [`<p><span class="stat">${inline(metric.value)}</span></p>`] };
  }
  if (name === "media") return { lines: mediaLines(project, arg) };
  if (name === "media-grid") {
    return {
      blankBefore: true,
      lines: [
        `<div class="ph-grid">`,
        ...indent(2, arg.split(",").map((s) => phFigure(mediaBySlot(project, s.trim())))),
        `</div>`,
      ],
    };
  }
  if (name === "links") return { lines: linkLines(project.links ?? []) };
  throw new Error(`${project._file}: unknown directive {{${value}}}`);
}

function mediaLines(project, slot) {
  const m = mediaBySlot(project, slot);
  return m.type === "svg" ? svgFigure(m) : [phFigure(m)];
}

/* One link renders bare; two or more sit in a <p> with the leading ones spaced. */
function linkLines(links) {
  if (!links.length) return [];
  if (links.length === 1) return [anchor({ ...links[0], btn: true })];
  return [
    `<p>`,
    ...indent(
      2,
      links.map((l, i) =>
        anchor({ ...l, btn: true, style: i < links.length - 1 ? "margin-right:.6rem" : undefined })
      )
    ),
    `</p>`,
  ];
}

function renderCaseContent(project) {
  const out = [];
  const push = (blankBefore, lines) => {
    if (blankBefore && out.length) out.push("");
    out.push(...lines);
  };

  const cover = (project.media ?? []).find((m) => m.slot === "cover");
  if (cover) push(false, [phFigure(cover)]);

  for (const s of project.sections) {
    if (s.kind === "summary" || s.kind === "subtitle") continue;
    push(true, [`<h3>${inline(s.heading)}</h3>`]);
    for (const b of s.blocks) {
      if (b.type === "p") push(false, [`<p>${inline(b.text)}</p>`]);
      else if (b.type === "list") {
        push(false, [`<ul>`, ...indent(2, b.items.map((i) => `<li>${inline(i)}</li>`)), `</ul>`]);
      } else {
        const d = renderDirective(project, b.value);
        push(Boolean(d.blankBefore), d.lines);
      }
    }
  }
  return out;
}

/* ============================================================
   4. js/case-studies.js
   ============================================================ */
const jsString = (s) => JSON.stringify(s);
const jsKey = (k) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));
const jsTemplate = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

function buildCaseStudiesJs() {
  const out = [
    `/* GENERATED by scripts/build-content.mjs from content/ — do not edit.`,
    `   Edit content/projects/*.md and run \`node scripts/build-content.mjs\`.`,
    `   Case study content — condensed from the full Notion case studies. */`,
    `window.CASE_STUDIES = {`,
  ];
  caseStudies.forEach((p, i) => {
    const body = renderCaseContent(p);
    out.push(`  ${jsKey(p.id)}: {`);
    out.push(`    index: ${jsString(`${String(p.index).padStart(2, "0")} / ${p.client}`)},`);
    out.push(`    title: ${jsString(p.title)},`);
    out.push(`    subtitle:`);
    out.push(`      ${jsString(sectionText(p, "subtitle"))},`);
    out.push(`    meta: [${p.tags.map(jsString).join(", ")}],`);
    out.push(`    accentMeta: [${jsString(p.accentTag)}],`);
    out.push(`    content: \``);
    out.push(...indent(6, body).map(jsTemplate));
    out.push(`    \`,`);
    out.push(`  },${i < caseStudies.length - 1 ? "\n" : ""}`);
  });
  out.push(`};`);
  return out.join("\n") + "\n";
}

/* ============================================================
   5. Page regions

   The generator owns the inner HTML of each `<!-- content:NAME -->` region and
   nothing else: the skeleton, the section structure and the data-reveal /
   data-rise / data-lines hooks stay in the page where they belong.

   `data-count` used to be in that list. It is not emitted anywhere any more —
   see the note above factCell.
   ============================================================ */
function applyRegions(html, regions, file) {
  let out = lf(html);
  for (const [name, lines] of Object.entries(regions)) {
    const open = `<!-- content:${name} -->`;
    const close = `<!-- /content:${name} -->`;
    const start = out.indexOf(open);
    const end = out.indexOf(close, start);
    if (start === -1 || end === -1) {
      console.error(
        `✗ ${file}: region marker ${open} … ${close} not found.\n` +
          `  Generated regions are delimited in the page; the skeleton around them is hand-authored.`
      );
      process.exit(1);
    }
    /* Re-indent to whatever depth the opening marker sits at, so a region can be
       moved in the page without the generator caring. */
    const lineStart = out.lastIndexOf("\n", start) + 1;
    const at = out.slice(lineStart, start).length;
    const closeLineStart = out.lastIndexOf("\n", end) + 1;
    out =
      out.slice(0, start + open.length) +
      "\n" +
      indent(at, lines).join("\n") +
      (lines.length ? "\n" : "") +
      out.slice(closeLineStart);
  }
  return out;
}

function metaRegion(key) {
  const m = profile.meta[key];
  return [
    `<title>${inline(m.title)}</title>`,
    `<meta name="description" content="${escAttr(m.description)}">`,
    `<meta property="og:title" content="${escAttr(m.ogTitle)}">`,
    `<meta property="og:description" content="${escAttr(m.ogDescription)}">`,
    `<meta property="og:type" content="${escAttr(m.ogType)}">`,
    `<meta property="og:url" content="${escAttr(m.ogUrl)}">`,
    `<meta name="twitter:card" content="${escAttr(m.twitterCard)}">`,
    ``,
    `<!-- schema.org, generated from the same content/ source as the page above. -->`,
    `<script type="application/ld+json">${buildJsonLd()}</script>`,
  ];
}

const yearSpan = (s) => s.replace("{{year}}", `<span id="year">${profile.footer.fallbackYear}</span>`);

function footerRegion(key) {
  const f = profile.footer[key];
  return [`<span>${yearSpan(inline(f.copyright))}</span>`, anchor(f.link)];
}

/* ---------- index.html ---------- */
function heroRegion() {
  return [
    `<p class="hero__role t-label">${inline(profile.identity.role)}</p>`,
    `<h1 class="hero__title t-display t-display--hero">`,
    ...indent(
      2,
      profile.hero.titleLines.map(
        (w) => `<span class="hero__row"><span class="hero__word" data-rise>${inline(w)}</span></span>`
      )
    ),
    `</h1>`,
    `<div class="hero__body">`,
    `  <p class="hero__lede">${inline(profile.prose.heroLede)}</p>`,
    `  <div class="hero__actions">`,
    ...indent(4, profile.hero.actions.map((a) => anchor({ ...a, btn: true }))),
    `  </div>`,
    `</div>`,
  ];
}

/* A row may be `{ "ref": "availability" }` rather than literal text: the status
   line is also reported by get_profile and by llms.txt, and one string in two
   places is exactly the drift this pipeline exists to remove. */
const profileRows = profile.profileRows.map((r) => (r.ref ? profile[r.ref] : r));

function profileRegion() {
  return [
    `<dl class="profile mono">`,
    ...indent(
      2,
      profileRows.map(
        (r) =>
          `<div><dt>${inline(r.term)}</dt><dd${r.status === "ok" ? ' class="is-ok"' : ""}>${inline(
            r.value
          )}</dd></div>`
      )
    ),
    `</dl>`,
  ];
}

function cardGrid(items, cardClass, extraAttr, typeOf) {
  const out = [`<div class="card-grid">`];
  for (const it of items) {
    out.push(`  <article class="${cardClass}"${extraAttr}>`);
    const type = typeOf?.(it);
    if (type) out.push(`    <span class="card__type">${inline(type)}</span>`);
    out.push(`    <h3 class="card__title">${inline(it.title)}</h3>`);
    out.push(`    <p>${inline(it.body)}</p>`);
    out.push(`  </article>`);
  }
  out.push(`</div>`);
  return out;
}

const capabilitiesRegion = () =>
  cardGrid(capabilities, "card card--ruled", " data-reveal");

/* The Notable Projects grid. A card is `cardType` + `title` + `{#summary}` — and
   OPTIONALLY a `{#subtitle}`, which is the "more info on demand" field:

     "one is great, when I have time I will write bigger descriptions for all
      notable projects and we can add subtitle or something that the assistant
      could provide more info on demand."

   That field already exists and needs no schema change, now or later. Any
   project may carry a `{#subtitle}` section; the build only REQUIRES one when
   `hasCaseStudy` is true. On a card it is deliberately not rendered here — the
   card stays two lines — but it is emitted as `projects[].subtitle` in
   content.json and becomes the retrievable chunk `project:<id>#subtitle` the
   moment it has text in it. An absent one is an empty string and produces no
   chunk, so nine empty fields cost nothing and nothing has to change when the
   first one is written. */
const moreProjectsRegion = () =>
  cardGrid(
    cardProjects.map((p) => ({ title: p.title, body: section(p, "summary").blocks[0].text, cardType: p.cardType })),
    "card",
    " data-reveal",
    (p) => p.cardType
  );

function workIndexRegion() {
  const out = [`<ul class="idx" role="list">`];
  for (const p of caseStudies) {
    const chips = p.indexTags
      .map((t) => `<span class="chip${p.indexAccentTag === t ? " chip--solid" : ""}">${inline(t)}</span>`)
      .join("");
    out.push(
      `  <li>`,
      `    <button class="idx__row" data-project="${escAttr(p.id)}">`,
      `      <span class="idx__no mono">${String(p.index).padStart(2, "0")}</span>`,
      `      <span class="idx__main">`,
      /* A heading, not a span: these six are the page's flagship work, and the
         eight lesser cards below already carry <h3>. With a span here the
         heading outline listed the side projects and none of the case studies —
         the document's own priority, inverted. Styled entirely by .idx__name,
         so the element name is free: the foundation reset zeroes the UA margin
         and the class already pins font-family/size/weight/line-height/colour. */
      `        <h3 class="idx__name">${inline(p.indexClient ?? p.client)} <em>— ${inline(
        p.indexTitle ?? p.title
      )}</em></h3>`,
      `        <span class="idx__desc">${inline(section(p, "summary").blocks[0].text)}</span>`,
      `      </span>`,
      `      <span class="idx__tags">${chips}</span>`,
      `      <span class="idx__go mono" aria-hidden="true">View →</span>`,
      `    </button>`,
      `  </li>`
    );
  }
  out.push(`</ul>`);
  return out;
}

/* ---------- the unexpected facts, without the big numbers ----------

   There is no `.fact__num` here any more, and that is the owner's decision, not
   a simplification: "I don't like all the importance and big numbers on the
   unexpected facts, I am not an athlete to show these. I prefer them small and
   tidy." `facts.json` no longer carries `value`, `unit` or `count`; the whole
   fact is the label sentence, and 250 kg survives inside the sentence that
   claims it rather than as a headline numeral.

   TWO CONSEQUENCES FOR OTHER OWNERS, neither of them this file's to fix.
     · `data-count` is now emitted NOWHERE in the repo, so js/main.js's odometer
       — the [data-count] loop, its no-motion branch and the 4s stalled-ticker
       failsafe — has no elements to find. That machinery is dead, including the
       progressive-enhancement fix that made this emitter ship the real figure
       instead of the animation's first frame. It is js/'s to retire.
     · `.fact__num` is NOT dead CSS: evals/run.mjs writes its own `.facts` block
       into evals.html and that one still carries `fact__num`. The fact
       component's spec and story do document `data-count`, which now documents
       an unused hook — design-system's call. */
function factCell(f, surface) {
  const label = (surface === "cv" && f.cv?.label) || f.label;
  return [
    `<div class="fact">`,
    `  <span class="fact__title">${inline(f.title)}</span>`,
    `  <span class="fact__label">${inline(label)}</span>`,
    `</div>`,
  ];
}

function factsBlock(surface, attr) {
  return [
    `<div class="facts"${attr}>`,
    ...indent(2, facts.flatMap((f) => factCell(f, surface))),
    `</div>`,
  ];
}

function backgroundRegion() {
  const b = profile.prose.background;
  return [
    `<p class="t-lead notes__prose" data-lines>${inline(b.prose)}</p>`,
    `<p class="t-statement notes__statement" data-lines>${inline(b.statement)}</p>`,
    ``,
    `<p class="t-kicker notes__lead">${inline(b.kicker)}</p>`,
    ...factsBlock("site", " data-reveal"),
  ];
}

function skillsRegion(surface) {
  const attr = surface === "site" ? " data-reveal" : "";
  const out = [`<dl class="tools">`];
  for (const id of skills.order[surface]) {
    const g = skills.groups[id]?.[surface];
    if (!g) throw new Error(`skills.json: group "${id}" has no "${surface}" text but is in order.${surface}`);
    out.push(
      `  <div class="tools__row"${attr}>`,
      `    <dt>${inline(g.term)}</dt>`,
      `    <dd>${inline(g.text)}</dd>`,
      `  </div>`
    );
  }
  out.push(`</dl>`);
  return out;
}

function contactRegion() {
  const c = profile.contactSection;
  return [
    `<p class="tx__kicker t-kicker">${inline(profile.prose.contactKicker)}</p>`,
    `<a class="tx" href="mailto:${escAttr(profile.contact.email)}">`,
    `  <span class="tx__big t-display t-display--xl" data-rise>${c.bigLines
      .map(inline)
      .join("<br>")}</span>`,
    `  <span class="tx__mail mono">${inline(profile.contact.email)}</span>`,
    `</a>`,
    `<div class="link-grid" data-reveal>`,
    ...indent(2, c.links.map((l) => anchor(l))),
    `</div>`,
  ];
}

/* ---------- cv.html ---------- */
function cvHeadRegion() {
  return [
    `<p class="cv-head__role t-label">${inline(profile.identity.role)}</p>`,
    `<h1 class="cv-head__name t-display t-display--lg">${inline(profile.identity.name)}</h1>`,
    `<p class="cv-head__disciplines mono">${inline(profile.identity.disciplines.join(" · "))}</p>`,
    ``,
    `<ul class="cv-contact mono" role="list">`,
    ...indent(
      2,
      profile.cv.contactList.map(
        (c) => `<li>${c.href ? anchor(c) : inline(c.label)}</li>`
      )
    ),
    `</ul>`,
    ``,
    `<p class="cv-summary t-lead">${inline(profile.prose.cvSummary)}</p>`,
  ];
}

function openSourceRegion() {
  const os = profile.cv.openSource;
  return [
    ...profile.prose.cvOpenSource.map((p) => `<p>${inline(p)}</p>`),
    `<p class="cv-facts mono">${inline(profile.prose.cvOpenSourceFacts)}</p>`,
    `<div class="link-grid">`,
    ...indent(2, os.links.map((l) => anchor(l))),
    `</div>`,
    `<!-- Paper can't be clicked: the buttons above are replaced by their URLs in print. -->`,
    `<p class="print-only mono">${inline(os.printUrls.join(" · "))}</p>`,
  ];
}

/* `.entry__span` is FORMATTED from {start, end, note, location, mode} — never
   authored. "Jan 2026 – Present · Sofia · Hybrid" is a rendering of a date. */
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
function formatDate(v) {
  if (!v) return "Present";
  const m = String(v).match(/^(\d{4})(?:-(\d{2}))?$/);
  if (!m) throw new Error(`unparseable date "${v}" — use "YYYY" or "YYYY-MM"`);
  return m[2] ? `${MONTHS[Number(m[2]) - 1]} ${m[1]}` : m[1];
}
function formatPeriod(p) {
  const span = `${formatDate(p.start)} – ${formatDate(p.end)}`;
  return [span, p.note, p.location, p.mode].filter(Boolean).join(" · ");
}

function experienceRegion() {
  const out = [];
  experience.forEach((e, i) => {
    if (i) out.push("");
    out.push(`<article class="entry">`);
    out.push(`  <h3 class="entry__role">${inline(e.role)}</h3>`);
    out.push(`  <p class="entry__span">${inline(formatPeriod(e.period))}</p>`);
    out.push(
      `  <p class="entry__org">${inline(e.org)}${
        e.descriptor ? ` <em>— ${inline(e.descriptor)}</em>` : ""
      }</p>`
    );
    const bullets = e.sections.flatMap((s) => s.blocks.filter((b) => b.type === "list")).flatMap((b) => b.items);
    if (bullets.length) {
      out.push(`  <ul class="entry__list">`);
      out.push(...indent(4, bullets.map((b) => `<li>${inline(b)}</li>`)));
      out.push(`  </ul>`);
    }
    out.push(`</article>`);
  });
  return out;
}

function educationRegion() {
  return [
    `<dl class="tools">`,
    `  <div class="tools__row">`,
    `    <dt>${inline(education.labels.education)}</dt>`,
    `    <dd>${inline(
      education.education.map((e) => `${e.qualification} — ${e.institution}`).join(" · ")
    )}</dd>`,
    `  </div>`,
    `  <div class="tools__row">`,
    `    <dt>${inline(education.labels.languages)}</dt>`,
    `    <dd>${inline(
      education.languages.map((l) => `${l.language} (${l.level})`).join(" · ")
    )}</dd>`,
    `  </div>`,
    `</dl>`,
  ];
}

/* ============================================================
   6. content/dist/content.json — the retrieval index

   One chunk per section, plus precomputed BM25 term frequencies and corpus
   statistics. Deterministic by construction: no timestamps, stable ordering,
   so `--check` compares bytes and means it.
   ============================================================ */
/* Punctuation is trimmed from the ENDS of a token and never from the middle.
   A blanket split would be wrong in both directions here: leaving sentence
   punctuation on made `analytics` and `analytics.` two different terms, which
   halves IDF for both and silently loses every chunk where the word happened to
   end a sentence; but stripping punctuation everywhere would destroy tokens this
   corpus actually means — `200+`, `−40%`, `1:1`, `2.1`, `64×80`, `5–6`, `p5.js`,
   `tokens.json`, `build.mjs`, `case-studies.js`, `spec.md`. */
const EDGE_PUNCT = /^[.,;:!?"'’“”()[\]—–…·]+|[.,;:!?"'’“”()[\]—–…·]+$/g;

const tokenize = (s) =>
  s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .split(/[\s/·|]+/)
    .flatMap((raw) => {
      // Possessives are the same defect as trailing full stops: `wcag` and
      // `wcag's` are one term, not two.
      const t = raw.replace(EDGE_PUNCT, "").replace(/['’]s$/, "");
      // Word compounds keep splitting on the hyphen exactly as they always have
      // (`ai-ready` → ai, ready), so this change is the punctuation fix and
      // nothing else. Anything carrying a dot or a digit is an identifier or a
      // measurement and stays whole.
      return t.includes("-") && !/[.\d]/.test(t) ? t.split("-") : [t];
    })
    .filter((t) => t.length > 1 && t.length < 32);

const chunks = [];
/* Section kinds repeat within a single entity — the audit carries two
   {#approach} and two {#outcome} — so `entity#kind` is not unique on its own.
   Six of seventy-six ids collided before this. An ambiguous id makes a citation
   point at a section KIND rather than a passage, and passage-level precision is
   exactly what the provenance gate in lib/knowledge/schema.js exists to check;
   a citation that can mean two paragraphs cannot prove either one.

   Later collisions take an ordinal. The first keeps the bare id so the common
   single-section case stays readable — note this means inserting a new section
   ahead of an existing one of the same kind moves the bare id to the newcomer.
   That is acceptable because citations are validated against the current index
   on every request, never stored, so they are never stale in a way that matters. */
const seenChunkIds = new Set();

function addChunk(id, entity, kind, heading, text, cite) {
  /* elideStats BEFORE plain(): see the note beside it. Both fields are elided
     because build-vectors hashes `${heading}. ${text}` — a statistic in a
     heading would couple the cache just as tightly as one in the body. */
  const t = plain(elideStats(text));
  if (!t) return;
  let unique = id;
  for (let n = 2; seenChunkIds.has(unique); n++) unique = `${id}-${n}`;
  seenChunkIds.add(unique);
  chunks.push({ id: unique, entity, kind, heading: elideStats(heading), text: t, cite });
}

for (const p of projects) {
  const label = p.hasCaseStudy ? `${p.client} — ${p.title}` : p.title;
  const cite = { page: "/", anchor: "#work", project: p.id, label };
  for (const s of p.sections) {
    addChunk(`project:${p.id}#${s.kind}`, `project:${p.id}`, s.kind, s.heading, blocksToText(s.blocks), cite);
  }
}
for (const e of experience) {
  const cite = { page: "/cv", anchor: "#experience", experience: e.id, label: `${e.role} — ${e.org}` };
  for (const s of e.sections) {
    addChunk(`experience:${e.id}#${s.kind}`, `experience:${e.id}`, s.kind, s.heading, blocksToText(s.blocks), cite);
  }
}
for (const c of capabilities) {
  addChunk(`capability:${c.id}`, `capability:${c.id}`, "summary", c.title, c.body, {
    page: "/", anchor: "#about", label: c.title,
  });
}
for (const [id, g] of Object.entries(skills.groups)) {
  for (const surface of ["site", "cv"]) {
    if (!g[surface]) continue;
    addChunk(`skills:${id}:${surface}`, `skills:${id}`, "summary", g[surface].term, g[surface].text, {
      page: surface === "cv" ? "/cv" : "/", anchor: "#skills", label: g[surface].term,
    });
  }
}
/* The chunk text is the label sentence and nothing else. It used to be
   `${value} ${unit}. ${label}` — a headline numeral glued to its caption — and
   both halves of that came out of the display fields the owner has now removed.
   "I can deadlift 250 kg" still carries its number because he wrote it into the
   sentence; "I ran a marathon" no longer carries `42 km`, so the tokens `42` and
   `km` leave the corpus with it. */
for (const f of facts) {
  addChunk(`fact:${f.id}`, `fact:${f.id}`, "summary", f.title, f.label, {
    page: "/", anchor: "#background", label: f.title,
  });
  if (f.cv?.label) {
    addChunk(`fact:${f.id}:cv`, `fact:${f.id}`, "summary", f.title, f.cv.label, {
      page: "/cv", anchor: "#unexpected", label: f.title,
    });
  }
}
addChunk("profile:hero", "profile", "summary", "Hero", profile.prose.heroLede, {
  page: "/", anchor: "#top", label: profile.identity.name,
});
addChunk("profile:cv-summary", "profile", "summary", "CV summary", profile.prose.cvSummary, {
  page: "/cv", anchor: "#top", label: profile.identity.name,
});
addChunk("profile:background", "profile", "context", "Background", profile.prose.background.prose, {
  page: "/", anchor: "#background", label: "Background",
});
addChunk("profile:background-statement", "profile", "context", "Background", profile.prose.background.statement, {
  page: "/", anchor: "#background", label: "Background",
});
addChunk(
  "profile:open-source",
  "profile",
  "system",
  "AI-ready design system",
  profile.prose.cvOpenSource.join(" ") + " " + profile.prose.cvOpenSourceFacts,
  { page: "/cv", anchor: "#open-source", label: "AI-ready design system" }
);
addChunk(
  "profile:education",
  "profile",
  "summary",
  "Education & languages",
  education.education.map((e) => `${e.qualification} — ${e.institution}`).join(" · ") +
    " · " +
    education.languages.map((l) => `${l.language} (${l.level})`).join(" · "),
  { page: "/cv", anchor: "#education", label: "Education & languages" }
);

/* BM25 needs three things at query time: per-chunk term frequencies, the
   document frequency of each term, and the corpus averages. All three are
   cheap to precompute and free at runtime — which is the whole argument for
   not standing up a service to do it. */
for (const c of chunks) {
  const terms = tokenize(`${c.heading} ${c.text}`);
  const tf = {};
  for (const t of terms) tf[t] = (tf[t] ?? 0) + 1;
  c.len = terms.length;
  c.tf = Object.fromEntries(Object.entries(tf).sort(([a], [b]) => (a < b ? -1 : 1)));
}
const df = {};
for (const c of chunks) for (const t of Object.keys(c.tf)) df[t] = (df[t] ?? 0) + 1;

function buildContentJson() {
  const doc = {
    $schema: "content/dist/content.schema — see content/CLAUDE.md",
    version: 1,
    generatedBy: "scripts/build-content.mjs — do not edit",
    /* The advertised statistics, verbatim from system.generated.json. This is
       the ONLY place in content.json the digits survive — chunk text elides
       them (see elideStats) — so get_system_facts is the answer path for
       "how many tokens?", exactly as its tool description says. `light`, `dark`
       and `print` are here because prose now interpolates `{{dark}}` and a
       reader who asks about the theme count must be able to get it from a tool
       rather than from a sentence. */
    system: {
      tokens: system.tokens,
      values: system.values,
      components: system.components,
      light: system.light,
      dark: system.dark,
      print: system.print,
    },
    profile: {
      identity: profile.identity,
      availability: profile.availability,
      contact: profile.contact,
      rows: profileRows,
      prose: {
        heroLede: plain(profile.prose.heroLede),
        cvSummary: plain(profile.prose.cvSummary),
        background: {
          prose: plain(profile.prose.background.prose),
          statement: plain(profile.prose.background.statement),
          kicker: plain(profile.prose.background.kicker),
        },
        openSource: profile.prose.cvOpenSource.map(plain),
        openSourceFacts: plain(profile.prose.cvOpenSourceFacts),
      },
    },
    capabilities,
    skills,
    education,
    facts,
    projects: projects
      .slice()
      .sort((a, b) => (a.hasCaseStudy === b.hasCaseStudy ? (a.index ?? a.order) - (b.index ?? b.order) : a.hasCaseStudy ? -1 : 1))
      .map((p) => ({
        id: p.id,
        index: p.index ?? null,
        order: p.order ?? null,
        title: p.title,
        client: p.client ?? null,
        indexClient: p.indexClient ?? null,
        indexTitle: p.indexTitle ?? null,
        cardType: p.cardType ?? null,
        hasCaseStudy: Boolean(p.hasCaseStudy),
        tags: p.tags ?? [],
        accentTag: p.accentTag ?? null,
        indexTags: p.indexTags ?? [],
        metrics: p.metrics ?? [],
        links: p.links ?? [],
        media: p.media ?? [],
        summary: sectionText(p, "summary"),
        subtitle: sectionText(p, "subtitle"),
        sections: p.sections
          .filter((s) => s.kind !== "summary" && s.kind !== "subtitle")
          .map((s) => ({ kind: s.kind, heading: s.heading, text: plain(blocksToText(s.blocks)) })),
      })),
    experience: experience.map((e) => ({
      id: e.id,
      role: e.role,
      org: e.org,
      descriptor: e.descriptor ?? null,
      period: e.period,
      span: formatPeriod(e.period),
      projects: e.projects ?? [],
      bullets: e.sections
        .flatMap((s) => s.blocks.filter((b) => b.type === "list"))
        .flatMap((b) => b.items)
        .map(plain),
    })),
    /* ---------- the design system's component contract, folded in ----------
       design-system/dist/components.json, verbatim. It is HERE rather than read
       directly by lib/knowledge because content.json is the one artefact that
       crosses that boundary; a consumer that opened design-system/dist/ for
       itself would add a second edge to the graph for no gain.

       Two properties this MUST keep, or a pure design-system change starts
       costing money again:
         · it is NOT chunked — no chunk is derived from it, so it cannot enter
           the build-vectors corpus hash;
         · it is NOT in `doc.manifest` — evals/run.mjs publishes
           `corpus.manifestChars` into results.json, so putting it in the
           manifest would invalidate the eval artefacts every time a CSS block
           gained a selector. */
    designSystem: {
      $derivedFrom: "design-system/dist/components.json (generated) — folded in verbatim",
      count: dsComponents.count,
      components: dsComponents.components,
    },
    /* ---------- /evals page prose, as a TEMPLATE ----------
       See content/evals.json for the full argument. Three properties matter:
         · the `{{evals:…}}` placeholders are left UNSUBSTITUTED — this build may
           not read evals/results.json (check-boundaries.mjs bans scripts/ →
           evals/), so the numbers are filled in by evals/run.mjs, which has both
           this artefact and the run it just produced;
         · `html` is rendered through the same `inline()` as every other
           sentence on the site, so the markdown subset and the no-raw-HTML rule
           hold here too;
         · like `designSystem`, it is NOT chunked and NOT in the manifest. */
    evalsPage: {
      $doc:
        "Hand-authored prose for evals.html section 04. Placeholders are filled by evals/run.mjs. " +
        "Not chunked, not in the manifest: changing it moves neither the vector corpus hash nor corpus.manifestChars.",
      reading: {
        region: evalsPage.reading.region,
        html: evalsPage.reading.paragraphs.map((p) => `<p>${inline(p)}</p>`),
        placeholders: evalsPage.reading.placeholders,
        review: evalsPage.reading.review,
      },
    },
    chunks,
    bm25: {
      N: chunks.length,
      avgdl: Number((chunks.reduce((n, c) => n + c.len, 0) / (chunks.length || 1)).toFixed(4)),
      df: Object.fromEntries(Object.entries(df).sort(([a], [b]) => (a < b ? -1 : 1))),
    },
  };
  /* The manifest is the corpus table of contents: every id, title and one-line
     summary, and nothing else. It is what lets a model know what exists without
     a retrieval round trip — and the most direct demonstration that this corpus
     does not need a vector database. */
  doc.manifest = {
    projects: doc.projects.map((p) => ({ id: p.id, title: p.title, client: p.client, tags: p.tags, summary: p.summary })),
    experience: doc.experience.map((e) => ({ id: e.id, role: e.role, org: e.org, span: e.span })),
    facts: facts.map((f) => ({ id: f.id, title: f.title })),
  };
  return JSON.stringify(doc, null, 2) + "\n";
}

/* ============================================================
   7. site.jsonld + llms.txt
   ============================================================ */
function buildJsonLd() {
  const person = {
    "@type": "Person",
    "@id": `${profile.contact.site}/#person`,
    name: profile.identity.name,
    jobTitle: profile.identity.role,
    description: plain(profile.prose.cvSummary),
    email: `mailto:${profile.contact.email}`,
    telephone: profile.contact.phone,
    url: profile.contact.site,
    address: {
      "@type": "PostalAddress",
      addressLocality: profile.identity.location.city,
      addressCountry: profile.identity.location.country,
    },
    sameAs: [profile.contact.linkedin, profile.contact.repo],
    knowsAbout: skills.order.cv.map((id) => skills.groups[id].cv.term),
    alumniOf: education.education.map((e) => ({ "@type": "EducationalOrganization", name: e.institution })),
    knowsLanguage: education.languages.map((l) => ({ "@type": "Language", name: l.language })),
    worksFor: { "@type": "Organization", name: experience[0].org },
  };
  const works = caseStudies.map((p) => ({
    "@type": "CreativeWork",
    "@id": `${profile.contact.site}/#${p.id}`,
    name: p.title,
    headline: `${p.client} — ${p.title}`,
    abstract: sectionText(p, "subtitle"),
    description: sectionText(p, "summary"),
    keywords: p.tags,
    creator: { "@id": `${profile.contact.site}/#person` },
  }));
  return JSON.stringify({ "@context": "https://schema.org", "@graph": [person, ...works] });
}

function buildLlmsTxt() {
  const L = [];
  L.push(`# ${profile.identity.name} — ${profile.identity.role}`);
  L.push(``);
  L.push(`> ${plain(profile.prose.heroLede)}`);
  L.push(``);
  L.push(
    `Generated by scripts/build-content.mjs from content/ — the single source for every`,
    `word on ${profile.contact.site}. Do not edit this file.`
  );
  L.push(``);
  L.push(`Structured index for agents: ${profile.contact.site}/content/dist/content.json`);
  L.push(``);
  L.push(`## Profile`);
  L.push(``);
  L.push(`- Location: ${profile.identity.location.full}`);
  L.push(`- Availability: ${profile.availability.value}`);
  L.push(`- Email: ${profile.contact.email}`);
  L.push(`- LinkedIn: ${profile.contact.linkedin}`);
  L.push(`- Source repo: ${profile.contact.repo}`);
  L.push(``);
  L.push(plain(profile.prose.cvSummary));
  L.push(``);
  L.push(`## Case studies`);
  L.push(``);
  for (const p of caseStudies) {
    L.push(`### ${String(p.index).padStart(2, "0")} · ${p.client} — ${p.title}`);
    L.push(``);
    L.push(sectionText(p, "summary"));
    L.push(``);
    L.push(`Tags: ${p.tags.join(", ")}`);
    if (p.metrics?.length) L.push(`Metrics: ${p.metrics.map((m) => `${m.value} ${m.label}`).join("; ")}`);
    L.push(``);
  }
  L.push(`## Other projects`);
  L.push(``);
  for (const p of cardProjects) L.push(`- **${p.title}** (${p.cardType}) — ${sectionText(p, "summary")}`);
  L.push(``);
  L.push(`## Experience`);
  L.push(``);
  for (const e of experience) {
    L.push(`### ${e.role} — ${e.org}${e.descriptor ? ` (${e.descriptor})` : ""}`);
    L.push(``);
    L.push(formatPeriod(e.period));
    L.push(``);
    for (const b of e.sections.flatMap((s) => s.blocks.filter((x) => x.type === "list")).flatMap((b) => b.items)) {
      L.push(`- ${plain(b)}`);
    }
    L.push(``);
  }
  L.push(`## Skills`);
  L.push(``);
  for (const id of skills.order.cv) L.push(`- **${skills.groups[id].cv.term}** — ${skills.groups[id].cv.text}`);
  L.push(``);
  L.push(`## Education & languages`);
  L.push(``);
  for (const e of education.education) L.push(`- ${e.qualification} — ${e.institution}`);
  for (const l of education.languages) L.push(`- ${l.language} (${l.level})`);
  L.push(``);
  L.push(`## The design system`);
  L.push(``);
  L.push(
    `${system.tokens} tokens carrying ${system.values} values across light, dark and print · ` +
      `${system.components} components, each enforced as CSS + spec.md + Storybook story.`
  );
  L.push(``);
  return L.join("\n");
}

/* ============================================================
   8. Emit / check
   ============================================================ */
const indexRegions = {
  meta: metaRegion("index"),
  hero: heroRegion(),
  profile: profileRegion(),
  capabilities: capabilitiesRegion(),
  "work-index": workIndexRegion(),
  "more-projects": moreProjectsRegion(),
  background: backgroundRegion(),
  skills: skillsRegion("site"),
  contact: contactRegion(),
  footer: footerRegion("index"),
};

const cvRegions = {
  meta: metaRegion("cv"),
  "cv-head": cvHeadRegion(),
  "open-source": openSourceRegion(),
  experience: experienceRegion(),
  skills: skillsRegion("cv"),
  education: educationRegion(),
  facts: factsBlock("cv", ""),
  footer: footerRegion("cv"),
};

const outputs = [
  ["js/case-studies.js", buildCaseStudiesJs()],
  ["index.html", applyRegions(read("index.html"), indexRegions, "index.html")],
  ["cv.html", applyRegions(read("cv.html"), cvRegions, "cv.html")],
  ["content/dist/content.json", buildContentJson()],
  ["content/dist/site.jsonld", buildJsonLd() + "\n"],
  ["llms.txt", buildLlmsTxt()],
];

mkdirSync(join(root, "content", "dist"), { recursive: true });

if (CHECK) {
  const stale = [];
  for (const [rel, want] of outputs) {
    const path = join(root, rel);
    if (!existsSync(path)) {
      stale.push(`${rel} is missing`);
      continue;
    }
    if (lf(readFileSync(path, "utf8")) !== lf(want)) stale.push(`${rel} is out of date`);
  }
  if (stale.length) {
    console.error(
      `✗ content check failed — generated files do not match content/:\n  - ${stale.join("\n  - ")}\n` +
        `  These files are GENERATED. Edit content/ and run:\n` +
        `    node design-system/scripts/build.mjs && node scripts/build-content.mjs`
    );
    process.exit(1);
  }
  /* ---------- nested-comment gate ----------
     HTML comments do not nest. A `<!--` inside a comment body means the parser
     already closed the comment at the first inner `-->`, and everything after
     it renders as visible text. This shipped: a hand-authored note explaining
     why a section has no region wrapped a literal `<!-- content:… -->` marker,
     and a paragraph of developer prose was live on the homepage above the Ask
     section. It survives review because the source reads as one comment. It is
     one regex to assert, so it is asserted. */
  const PAGES = ["index.html", "cv.html", "mcp.html", "evals.html"];
  const nested = [];
  for (const rel of PAGES) {
    const path = join(root, rel);
    if (!existsSync(path)) {
      nested.push(`${rel} is missing — it is a shipped page and must exist`);
      continue;
    }
    const text = lf(readFileSync(path, "utf8"));
    for (const m of text.matchAll(/<!--([\s\S]*?)-->/g)) {
      if (!m[1].includes("<!--")) continue;
      const line = text.slice(0, m.index).split("\n").length;
      nested.push(`${rel}:${line} — comment body contains a nested "<!--"`);
    }
  }
  if (nested.length) {
    console.error(
      `✗ nested comment check failed:\n  - ${nested.join("\n  - ")}\n` +
        `  HTML comments do not nest: the parser ends the comment at the FIRST\n` +
        `  "-->", so the rest of it renders as visible text on the page. To talk\n` +
        `  about a marker inside a comment, break the sequence — write it as\n` +
        `  "content:NAME" without the angle brackets.`
    );
    process.exit(1);
  }

  console.log(`✓ content check          (${outputs.length} generated files up to date)`);
  console.log(`✓ nested comment check   (${PAGES.length} pages, no comment contains "<!--")`);
} else {
  for (const [rel, text] of outputs) writeFileSync(join(root, rel), lf(text));
  console.log(`✓ js/case-studies.js     (${caseStudies.length} case studies)`);
  console.log(`✓ index.html             (${Object.keys(indexRegions).length} regions)`);
  console.log(`✓ cv.html                (${Object.keys(cvRegions).length} regions)`);
  console.log(`✓ content/dist/content.json (${chunks.length} chunks, ${Object.keys(df).length} terms)`);
  console.log(`✓ content/dist/site.jsonld  (Person + ${caseStudies.length} CreativeWork)`);
  console.log(`✓ llms.txt`);
}
