#!/usr/bin/env node
/* ============================================================
   Stylesheet gate — zero dependencies.

   `node scripts/check-css.mjs`

   Six rules that the design system states in prose and, until now,
   nothing enforced. Prose does not survive contact with a deadline:
   the colour half of the token layer held for months because every
   colour had a semantic name and no ramp value was reachable outside
   tokens.json, while the TYPE half rotted to 89 font-size declarations
   at 40 distinct values — fourteen of them inside a single 0.34rem
   band, rendering at 1280px as 10.88 / 11.2 / 11.52 / 12.48 / 12.8 /
   13.6 / 14.08 / 14.4 / 14.72px. Nobody chose those. They accumulated,
   because nothing said no.

   WHY THIS LIVES HERE AND NOT IN design-system/scripts/build.mjs.
   The rules span the design system AND the site's four page
   stylesheets and js/. `build.mjs` is the root of the dependency
   graph (ARCHITECTURE.md) and must not read outside its own slice —
   check-boundaries.mjs asserts exactly that. `scripts/` is the layer
   that legitimately sees the whole repo, so a cross-slice assertion
   belongs here. build.mjs keeps what is derivable from its own
   sources: token emission, component coverage, the spec↔CSS contract.

   THE RULES

   1. No literal `font-size` in components.css or a page stylesheet.
      Every size is a `--text-*` step, or the keyword `inherit` — an
      inherited size is a relationship, not a value, and the scale is
      whatever the parent already picked.

   2. No `prefers-color-scheme` outside design-system/dist/. A colour
      that differs in dark is a token with a `dark` value; the build
      emits the query. js/theme.js is the one sanctioned exception:
      it is the control that READS the preference.

   3. No hex / rgb() / hsl() literal in components.css, css/ or js/.
      Composition through a token — `rgba(var(--accent-rgb), 0.4)` in
      CSS, `rgba(${palette.cell}, ${a})` in JS — is the supported way
      to build a colour at runtime and is allowed.

   4. No `border`, and no px width/height, on a skeleton selector.
      Borders change fr-track math; inset box-shadows do not. See
      design-system/components/skeleton/spec.md.

   5. At most one `.btn--solid` per shipped page. The chat composer's
      submit is exempt: it is the primary action of its own surface
      and the chat spec canonises it as `.btn.btn--solid.chat__send`.

   6. A ceiling on the automata's visible column counts. The squares
      are real divs — 496 of them, ~58.5% of index.html's nodes — and
      js/automata.js derives everything else from `vc`. This is the
      one change class in the repo with a quadratic blast radius and
      no check; see the block at the bottom for the arithmetic.

   NOT CHECKED, DELIBERATELY: literal spacing. `mm` in cv.css's print
   block is a physical fact about a sheet of A4, not a step on a
   rhythm ramp, and `padding-bottom: 2px` under a text underline is an
   optical offset. A rule that flagged those would be wrong more often
   than right, and a gate people learn to override is worse than none.
   ============================================================ */
import { readFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const rel = (p) => relative(root, p).split(sep).join("/");

/* ---------- what we look at ---------- */
const STYLESHEETS = [
  join(root, "design-system", "css", "components.css"),
  ...(existsSync(join(root, "css"))
    ? readdirSync(join(root, "css"))
        .filter((f) => f.endsWith(".css"))
        .sort()
        .map((f) => join(root, "css", f))
    : []),
];

const SKIP_JS_DIRS = new Set(["vendor", "node_modules"]);
function jsFiles(dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith(".") || SKIP_JS_DIRS.has(e.name)) continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) jsFiles(p, out);
    else if (/\.(mjs|js|cjs)$/.test(e.name)) out.push(p);
  }
  return out;
}
/* A generated file is not a place anyone can fix a violation, and its
   content is prose from another slice: js/case-studies.js quotes the
   string "prefers-color-scheme" inside a <code> tag, in a case study
   ABOUT not having one. Gate the sources, not the outputs. */
const isGenerated = (src) => /generated\b[\s\S]{0,60}do not edit|GENERATED by/i.test(src.slice(0, 600));

const SITE_JS = jsFiles(join(root, "js")).filter((f) => !isGenerated(readFileSync(f, "utf8")));
/* js/theme.js is the theme CONTROL: reading the OS preference is its job. */
const PCS_EXEMPT = new Set(["js/theme.js"]);

const HTML_PAGES = readdirSync(root)
  .filter((f) => f.endsWith(".html"))
  .sort()
  .map((f) => join(root, f));

/* ---------- helpers ----------
   Comments are blanked rather than removed, so every offset below still
   maps to a real line in the real file — a gate that reports the wrong
   line number is a gate people stop reading. */
const blankComments = (s) =>
  s.replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, " "))
   .replace(/(^|[^:])\/\/[^\n]*/g, (m, p1) => p1 + " ".repeat(m.length - p1.length));

const lineAt = (src, index) => src.slice(0, index).split("\n").length;

/* A brace walk, not a regex: a regex cannot tell `@media (…) {` from a rule
   and would report `50%` inside @keyframes as a selector. Yields every
   declaration with the selector that owns it. */
function declarations(src) {
  const out = [];
  const stack = [];
  let buf = "";
  let start = 0;
  for (let i = 0; i < src.length; i++) {
    const ch = src[i];
    if (ch === "{") {
      const prelude = buf.trim();
      buf = "";
      start = i + 1;
      stack.push(
        prelude.startsWith("@")
          ? { type: prelude.startsWith("@keyframes") ? "keyframes" : "at", sel: prelude }
          : { type: "rule", sel: prelude.replace(/\s+/g, " ") }
      );
    } else if (ch === ";" || ch === "}") {
      const text = buf.trim();
      const top = stack[stack.length - 1];
      if (text && top && top.type === "rule") {
        const c = text.indexOf(":");
        if (c > 0) {
          out.push({
            prop: text.slice(0, c).trim().toLowerCase(),
            value: text.slice(c + 1).trim(),
            sel: top.sel,
            index: start + buf.length - buf.trimStart().length,
          });
        }
      }
      buf = "";
      start = i + 1;
      if (ch === "}") stack.pop();
    } else {
      buf += ch;
    }
  }
  return out;
}

const problems = [];
const at = (file, src, index) => `${rel(file)}:${lineAt(src, index)}`;

/* ============ 1. literal font-size ============ */
const FONT_SIZE_OK = /^(var\(\s*--[a-z0-9-]+\s*(,[^)]*)?\)|inherit|initial|unset|revert|revert-layer)$/i;
let sizedDecls = 0;

for (const file of STYLESHEETS) {
  const raw = readFileSync(file, "utf8");
  const src = blankComments(raw);
  for (const d of declarations(src)) {
    if (d.prop === "font-size") {
      sizedDecls++;
      if (!FONT_SIZE_OK.test(d.value.replace(/\s*!important$/, ""))) {
        problems.push(
          `${at(file, raw, d.index)}  \`${d.sel} { font-size: ${d.value} }\` is a literal size.\n` +
            `      Use a --text-* step from design-system/tokens/tokens.json. If no step fits, add one there — ` +
            `a size that exists in only one place is drift, not a decision.`
        );
      }
    }
    /* The `font` shorthand can smuggle a size in. `font: inherit` cannot. */
    if (d.prop === "font" && /\d/.test(d.value)) {
      problems.push(
        `${at(file, raw, d.index)}  \`${d.sel} { font: ${d.value} }\` sets a size through the shorthand — ` +
          `use \`font-size: var(--text-*)\` so the gate can see it.`
      );
    }
  }
}

/* ============ 2. prefers-color-scheme ============ */
for (const file of [...STYLESHEETS, ...SITE_JS]) {
  if (PCS_EXEMPT.has(rel(file))) continue;
  const raw = readFileSync(file, "utf8");
  const src = blankComments(raw);
  const i = src.indexOf("prefers-color-scheme");
  if (i !== -1) {
    problems.push(
      `${at(file, raw, i)}  mentions \`prefers-color-scheme\`. Dark is a token, not a query: ` +
        `add a \`dark\` value beside the light one in tokens.json and the build emits both the media query ` +
        `and the pinned-theme override. (design-system/dist/ and js/theme.js are the only places it may appear.)`
    );
  }
}

/* ============ 3. colour literals ============ */
const HEX = /#(?:[0-9a-f]{8}|[0-9a-f]{6}|[0-9a-f]{3,4})(?![0-9a-z_-])/gi;
const FUNC = /\b(rgba?|hsla?|hwb|lab|lch|oklab|oklch|color)\((?:[^()]|\([^()]*\))*\)/gi;

for (const file of [...STYLESHEETS, ...SITE_JS]) {
  const raw = readFileSync(file, "utf8");
  const src = blankComments(raw);
  for (const m of src.matchAll(HEX)) {
    problems.push(
      `${at(file, raw, m.index)}  hex literal \`${m[0]}\`. Colours are born in tokens.json and reach here as \`var(--…)\`.`
    );
  }
  for (const m of src.matchAll(FUNC)) {
    const composed = m[0].includes("var(") || m[0].includes("${");
    if (!composed && /\d/.test(m[0])) {
      problems.push(
        `${at(file, raw, m.index)}  colour literal \`${m[0]}\`. Compose from a token — ` +
          `\`rgba(var(--accent-rgb), 0.4)\` — or add the colour to tokens.json.`
      );
    }
  }
}

/* ============ 4. skeleton: no borders, no px sizes ============ */
const SKELETON = /\.(sheet|band|rail|well|strip|sq)\b/;
const ZEROISH = /^(0|none|0\s+none|unset|initial)$/i;

for (const file of STYLESHEETS) {
  const raw = readFileSync(file, "utf8");
  const src = blankComments(raw);
  for (const d of declarations(src)) {
    if (!SKELETON.test(d.sel)) continue;
    if (/^border(-(top|right|bottom|left|block|inline|width|style|color))?$/.test(d.prop) && !ZEROISH.test(d.value)) {
      problems.push(
        `${at(file, raw, d.index)}  \`${d.sel} { ${d.prop}: ${d.value} }\` — the skeleton never uses borders. ` +
          `A border changes the fr-track math; an inset box-shadow does not. See design-system/components/skeleton/spec.md.`
      );
    }
    if (/^(min-|max-)?(width|height)$/.test(d.prop) && /\d\s*px/.test(d.value)) {
      problems.push(
        `${at(file, raw, d.index)}  \`${d.sel} { ${d.prop}: ${d.value} }\` — skeleton elements derive every ` +
          `dimension from the band's fr tracks. A px size here desynchronises the squares from the layout.`
      );
    }
  }
}

/* ============ 5. one .btn--solid per page ============ */
const CLASS_ATTR = /class="([^"]*)"/g;
const solidCounts = [];
for (const file of HTML_PAGES) {
  const raw = readFileSync(file, "utf8");
  let n = 0;
  for (const m of raw.matchAll(CLASS_ATTR)) {
    const cls = m[1].split(/\s+/);
    if (cls.includes("btn--solid") && !cls.includes("chat__send")) n++;
  }
  solidCounts.push([rel(file), n]);
  if (n > 1) {
    problems.push(
      `${rel(file)} has ${n} \`.btn--solid\` outside the chat composer. One primary action per view — ` +
        `demote the others to \`.btn\`. (design-system/components/button/spec.md)`
    );
  }
}

/* ============ 6. the automata's DOM budget ============
   A static stylesheet check cannot count DOM nodes: every `.sq` is created
   by js/automata.js at runtime, so it appears in no shipped artefact. What
   IS static is the input the node count is a function of, and that function
   is not linear.

     rail    size = clientWidth / vc
             vr   = floor(clientHeight / size) = floor(clientHeight·vc / clientWidth)
             nodes = vc · vr = vc² · (clientHeight / clientWidth)

   Raising a rail's visible column count from 2 to 4 does not double the
   rails, it QUADRUPLES them — the squares get narrower, so more of them fit
   down the band as well as across it. The strip is linear (`vr` is pinned at
   2), so its ceiling is looser.

   Measured today: 496 `.sq` divs on index.html, 58.5% of the document, at
   rail vc = 2 and strip vc = 24. The ceilings below leave one step of
   headroom each and exist so that a one-character edit cannot silently
   triple the page. If you need to pass one, that is a decision worth making
   on purpose: raise the number here, in the same commit, with the new node
   count measured. */
const AUTOMATA = join(root, "js", "automata.js");
const VC = /const\s+vc\s*=\s*MOBILE\.matches\s*\?\s*(\d+)\s*:\s*(\d+)\s*;/g;
/* `measured` is the value that produced the 496-node baseline in the comment
   above. It is stated rather than read back, so the failure message keeps
   quoting the number the measurement was taken at even while the file in
   front of it says something else. */
const CEILINGS = {
  rail: { max: 3, measured: 2, growth: "quadratically (vc² — narrower squares also stack deeper)" },
  strip: { max: 32, measured: 24, growth: "linearly (the strip is pinned to 2 visible rows)" },
};
const vcFound = { rail: null, strip: null };

if (!existsSync(AUTOMATA)) {
  problems.push(`js/automata.js is missing — rule 6 has nothing to measure. Update scripts/check-css.mjs.`);
} else {
  const raw = readFileSync(AUTOMATA, "utf8");
  const src = blankComments(raw);
  const hits = [...src.matchAll(VC)];
  for (const m of hits) {
    /* The two declarations are told apart by what the `return` beside each one
       reaches for, not by their order in the file: the rail's geometry adds
       HIDDEN_COLS to its sim width, the strip's uses STRIP_SIM_ROWS. */
    const after = src.slice(m.index, m.index + 240);
    const kind = after.includes("HIDDEN_COLS") ? "rail" : after.includes("STRIP_SIM_ROWS") ? "strip" : null;
    if (!kind || vcFound[kind] !== null) continue;
    vcFound[kind] = { mobile: Number(m[1]), desktop: Number(m[2]), index: m.index };
  }

  if (!vcFound.rail || !vcFound.strip) {
    /* Fail loudly rather than pass silently. A gate that quietly stops finding
       the thing it guards is worse than no gate: it reports success forever. */
    problems.push(
      `js/automata.js: rule 6 could not find both visible-column constants ` +
        `(found ${hits.length} \`const vc = MOBILE.matches ? n : m\`; rail=${Boolean(vcFound.rail)} strip=${Boolean(vcFound.strip)}). ` +
        `The geometry was refactored — re-derive the DOM budget and update rule 6 in scripts/check-css.mjs rather than deleting it.`
    );
  } else {
    for (const [kind, { max, measured, growth }] of Object.entries(CEILINGS)) {
      const { mobile, desktop, index } = vcFound[kind];
      const worst = Math.max(mobile, desktop);
      if (worst > max) {
        const impact =
          kind === "rail"
            ? `going from ${measured} to ${worst} is not ${(worst / measured).toFixed(1)}× the squares, ` +
              `it is ${((worst / measured) ** 2).toFixed(1)}×`
            : `going from ${measured} to ${worst} puts ${(worst / measured).toFixed(1)}× the divs in every strip`;
        problems.push(
          `${at(AUTOMATA, raw, index)}  ${kind} visible columns = ${worst}, ceiling ${max}. ` +
            `Every square is a real div and the ${kind} node count grows ${growth} — so ${impact}. ` +
            `The baseline this ceiling was set against: 496 \`.sq\` divs on index.html, 58.5% of the document, ` +
            `at rail vc=${CEILINGS.rail.measured} / strip vc=${CEILINGS.strip.measured}. ` +
            `If the new number is deliberate, raise the ceiling in scripts/check-css.mjs in the same commit and ` +
            `record the node count you measured — this ceiling is arithmetic, not taste.`
        );
      }
    }
  }
}

/* ---------- report ---------- */
if (problems.length) {
  console.error(`✗ css check failed (${problems.length}):\n  - ${problems.join("\n  - ")}`);
  process.exit(1);
}
console.log(
  `✓ css check              (${STYLESHEETS.length} stylesheets, ${SITE_JS.length} site scripts, ` +
    `${HTML_PAGES.length} pages · ${sizedDecls} font-size declarations, all tokens · ` +
    `0 colour literals · 0 prefers-color-scheme · skeleton clean · ` +
    `${solidCounts.map(([f, n]) => `${f.replace(/\.html$/, "")}:${n}`).join(" ")} solid buttons · ` +
    `automata vc rail ${vcFound.rail.desktop}/${vcFound.rail.mobile} ≤ ${CEILINGS.rail.max}, ` +
    `strip ${vcFound.strip.desktop}/${vcFound.strip.mobile} ≤ ${CEILINGS.strip.max})`
);
